package main

// A comment in this repository is public, so it may not point a reader at a document
// the repository does not ship: a path under the maintainer's private `.kiro` tree, a
// bare `<name>.md` that is not one of this repo's own files or a file marotte's
// product reads, a `#<doc>` pointer, or a private document's name written bare. The
// names are matched by hash, because a list of them would itself publish them.

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"go/scanner"
	"go/token"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"testing"
	"unicode"
)

// productDocNames are document names marotte's product reads or writes, so a comment
// describing that behaviour names them legitimately.
var productDocNames = map[string]bool{
	"environment.md":  true, // generated by internal/steering for every workspace
	"custom.md":       true, // the user's own instructions file, edited in Settings
	"SKILL.md":        true, // a Kiro skill's definition file, listed by the docs page
	"AGENTS.md":       true, // the agent-instructions file Kiro reads at a repo root
	"requirements.md": true, // spec documents the docs page groups per feature
	"design.md":       true,
	"tasks.md":        true,
	"bugfix.md":       true,
	"after-tasks.md":  true, // the KAS spec checkpoint the spec view answers
	"notes.md":        true, // the one illustration name comments use for a user file
}

var (
	// kiroDocPath is a concrete file under a private `.kiro` directory. A directory or a
	// glob (`.kiro/agents/`, `.kiro/agents/*.md`) is how marotte describes what it scans.
	kiroDocPath = regexp.MustCompile(`\.kiro/(steering|skills|scripts|agents|specs)/[\w./-]*[\w-]\.(md|py|mjs|sh|json)\b`)
	// kiroNamedDir is a named directory or a `{a,b}` group under a private `.kiro`
	// directory: either one names private files however the path ends.
	kiroNamedDir = regexp.MustCompile(`\.kiro/(steering|skills|scripts|agents|specs)/([\w-]+/|[\w./*-]*\{)`)
	// steeringDocPath is a `steering/<name>.md` reference outside `.kiro/`.
	steeringDocPath = regexp.MustCompile(`(^|[^\w./-])steering/([\w-][\w.-]*\.md)\b`)
	// bareDocName is a `<name>.md` token not reached through a path or a URL.
	bareDocName = regexp.MustCompile(`(^|[^\w.%/-])([\w-][\w.-]*\.md)\b`)
	// marotteDocName names one of the app's own design documents, which never ship.
	marotteDocName = regexp.MustCompile(`\bmarotte(-[a-z]+)*\.md\b`)
	// hashDocRef is a `#<name>` pointer to a document of the app or its toolchain,
	// which fires whatever the code defines.
	hashDocRef = regexp.MustCompile(`(^|[\s(\x60'"])#(marotte(-[a-z]+)*|kiro-[a-z]+(-[a-z]+)*|web-terminal-[a-z]+(-[a-z]+)*)([^\w-]|$)`)
	// hashName is any hyphenated `#<name>`: a pointer unless the name is something the
	// sources define outside comments, such as the element id in `#web-view`.
	hashName = regexp.MustCompile(`(^|[\s(\x60'"])#([a-z][a-z0-9]*(-[a-z0-9]+)+)([^\w-]|$)`)
	// bareDocStem is a hyphenated `<name>-rulebook`, or a `§` section citation of a
	// document of the families above, written with neither `#` nor `.md`.
	bareDocStem = regexp.MustCompile(`(^|[^\w./#@-])([a-z]+-rulebook|(marotte|kiro|web-terminal)(-[a-z]+)+\s*§)`)
	codeToken   = regexp.MustCompile(`[\w-]+`)
	// stemToken is a lowercase word, hyphenated or not, that knownStemRefs hashes.
	stemToken = regexp.MustCompile(`[a-z][a-z0-9]*(-[a-z0-9]+)*`)
	// sectionCite is what follows a document name cited by section: `§` or a quoted title.
	sectionCite = regexp.MustCompile(`^\s*(§|"[A-Z])`)
)

// knownStems holds the first 16 hex digits of the SHA-256 of each document stem in the
// maintainer's private steering set. Regenerate it from that directory with:
//
//	for f in *.md; do printf %s "${f%.md}" | sha256sum | cut -c1-16; done
var knownStems = func() map[string]bool {
	set := map[string]bool{}
	for h := range strings.FieldsSeq(`
012a653f42db9044 05d131b75cc2a753 06cf5b96eca79a03 07d907bcb31655dc 0bcd728f4324a803 0c1f7f3108b9dc7c
0d5a011050205b39 0faee5c5f42eebd4 0fd04bc364d66a70 11a7fe42b3e3235b 145cf109484a7a7d 1669a1013e1f0f57
16d231429d0199c2 177a7ea3611fe6b1 19687460032e31fa 1b158839f8aa339e 1c0f2b8a7d5ea781 1c8f936de110baa9
20e8cdb5b4093e18 21b747de22dbb757 244d70ee4683876a 27e0a4238214b0f3 2b0dcdd40016096b 2fc20975c6d52c00
303d4d3c42510a26 31182319f2fc98f9 33559d24c650ae38 33cfdcd7d72ecedf 34ba5ecd2347a565 37a854952ffc23b6
38f07265e5d92893 3a7382430ac92803 3cd564db50fccc8f 3ee591fcb25f09a0 40fc00fa1d13df5d 420c352eea8797be
44c3f6f83c39094f 46b4b524c68556f0 4b5e57f6eb2f42b9 4ca303a3bf7ddf7b 4cd0e21a9a0795a1 4f881a1a3db524da
500e8d2c01015fbb 520cdb563bf80b19 5491d8106908e03a 55b95f14512b10d6 56977b5ae3300aa4 58ee00072efbff71
5ab2a0b7488fbbb3 5d1c3ed5059b9064 5d2d3ceb7abe5523 5e92499d63592222 5ff73b4804620b07 614b1adce676994c
61946c94a43ed3ae 62484e22a6a5ade1 659d988c7bad9d27 6b4021c5c51645a2 6ba1ccdc6bfaff79 6e6c429183062d65
708117346fea6751 7124ddae77f1359b 74de07c4e919534b 7775ded789ee9769 780107e3f01a41db 7843221d63dabca8
7b26e4c0eb7d5a15 7c301b6396a715a9 83c2efa92fb5598a 83dd46ce66dd5598 83ef92353e592a76 8ac20d8c772b887f
8bb6922758ad870f 8ea20d7601daf25b 90305a4228bedb99 913b1d298ca9979d 922c8b860a58fdbc 92c36045af636d0c
932e19e0f5b79c03 949c872e74776cef 9502c0830e76622c 969545dde1584d88 980f52e021a032d5 98a031a699f4e488
997568b868a5a5d5 9b43cbc5010a1908 9e16ad4c32210e16 9f22321ae5703f7b 9f3a240916adc275 a02ba163f3a02db2
a2534aa4e36f2989 a33428cbc33ddd9b a365b36d190f46db a376267626fc2bc8 a485ec6d47de9fbd a56f226e4dd67057
a5a425b87fea0fe8 a8792157cb4f27fb aea028c2b5cf9178 b0019ef18d89eaa8 b1467a4c8116c29d b2de2480c3ebd219
b4a42c3843db2473 b5ffa2b60f3a2598 b6b674c8251eb34d ba5285161ba6eed0 bc378f4433cfa391 bdf49c3c3882102f
c2186bc47c349a4a c2c5f5673f7e53ff c41fae5186560782 c48a0c55ab8a2dd2 c846e2988a073bce c8ea72e56a1d450a
cace491b69555e8d ce635c4eabff5e4f cf299109dee20171 cf80cd8aed482d5d d0334f008a9e3429 d07915cde0dee19c
d2110fd79028b647 d6e0ff2b7a534a97 d791d4dae5d930e5 d9e97184f411b5ff da14a33ad09acf0c de15986752061435
de8b3e42e7ac0278 df959e0bb356780c e296d81ff5d146d0 e33539a47126eee9 e3400d038ebc2d2a e64ddfef8fa7b1c2
e75fe741533c59b9 e7d3799ecc09f5cb ebf58a8a5240a087 ed2dee336938286e edde7ebafe908447 ee871105e875f3de
f0d831b004f71460 f3be092176e2abda f71af02bbaaa6f4f f9d35d43770d3909 fe3811fe21af748f fe9bbd400bb6cb31
ffa4299909ef865f
`) {
		set[h] = true
	}
	return set
}()

func stemHash(s string) string {
	sum := sha256.Sum256([]byte(s))
	return hex.EncodeToString(sum[:8])
}

// knownStemRefs reports a private document named by its bare stem: anywhere when the
// stem is hyphenated, and a single-word stem only after `#` or before a section
// citation, since those are ordinary words. A stem the sources define outside comments
// (a public package such as `web-terminal-ui`) passes unless a section is cited. A
// token reached through a path, a URL or a file extension is not a bare name.
func knownStemRefs(line string, defined, stems map[string]bool) []string {
	var refs []string
	for _, ix := range stemToken.FindAllStringIndex(line, -1) {
		tok, rest := line[ix[0]:ix[1]], line[ix[1]:]
		var prev byte
		if ix[0] > 0 {
			prev = line[ix[0]-1]
		}
		path := prev != 0 && strings.IndexByte("./@-_\\", prev) >= 0 || 'A' <= prev && prev <= 'Z' ||
			'0' <= prev && prev <= '9' || strings.HasPrefix(rest, "/") ||
			len(rest) > 1 && rest[0] == '.' && (unicode.IsLetter(rune(rest[1])) || unicode.IsDigit(rune(rest[1])))
		if path || len(rest) > 0 && (rest[0] == '_' || 'A' <= rest[0] && rest[0] <= 'Z') || !stems[stemHash(tok)] {
			continue
		}
		cited := sectionCite.MatchString(rest)
		hyphenated := strings.Contains(tok, "-")
		switch {
		case cited:
		case prev == '#' && hyphenated: // hashDocRef and hashName own `#a-b`
			continue
		case !hyphenated && prev != '#', defined[tok], publicProjects[tok]:
			continue
		}
		refs = append(refs, tok)
	}
	return refs
}

// publicProjects are public repositories whose name a private document shares; a
// comment names the project, so the bare name passes unless a section is cited.
var publicProjects = func() map[string]bool {
	set := map[string]bool{}
	for name := range strings.FieldsSeq(`cert-converter docker-age docker-caddy
		docker-fclones-scheduler docker-keepalived docker-nut-upsd docker-radvd
		docker-renovate-scheduler docker-rsync-scheduler docker-smtp-relay docker-static-web
		github-scout pg-autodump plex-exporter plex-language-sync registry-stats seadex-scout
		tautulli-remap tool-catalog ui-primitives web-terminal-engine web-terminal-glyphs
		web-terminal-kiro web-terminal-server web-terminal-ui`) {
		set[name] = true
	}
	return set
}()

type commentSpan struct {
	text string
	line int
}

// privateDocRefs returns the private-document references in one comment line. code is
// the file's non-comment text: a `.md` name the file builds there is a fixture the
// comment describes, not a pointer. defined holds every word of the repository's
// non-comment text.
func privateDocRefs(line, code string, shipped, defined map[string]bool) []string {
	allowed := func(name string) bool {
		return shipped[name] || productDocNames[name] || containsToken(code, name)
	}
	var refs []string
	files := kiroDocPath.FindAllStringIndex(line, -1)
	for _, ix := range files {
		if m := line[ix[0]:ix[1]]; !strings.HasSuffix(m, "steering/environment.md") && !strings.HasSuffix(m, "steering/custom.md") {
			refs = append(refs, m)
		}
	}
	for _, ix := range kiroNamedDir.FindAllStringIndex(line, -1) {
		if !slices.ContainsFunc(files, func(f []int) bool { return f[0] == ix[0] }) {
			refs = append(refs, line[ix[0]:ix[1]])
		}
	}
	for _, m := range steeringDocPath.FindAllStringSubmatch(line, -1) {
		if !marotteDocName.MatchString(m[2]) && !allowed(m[2]) {
			refs = append(refs, "steering/"+m[2])
		}
	}
	refs = append(refs, marotteDocName.FindAllString(line, -1)...)
	for _, m := range bareDocName.FindAllStringSubmatch(line, -1) {
		if !marotteDocName.MatchString(m[2]) && !allowed(m[2]) {
			refs = append(refs, m[2])
		}
	}
	for _, m := range hashDocRef.FindAllStringSubmatch(line, -1) {
		refs = append(refs, "#"+m[2])
	}
	for _, m := range hashName.FindAllStringSubmatch(line, -1) {
		if !hashDocRef.MatchString(m[0]) && !defined[m[2]] {
			refs = append(refs, "#"+m[2])
		}
	}
	for _, m := range bareDocStem.FindAllStringSubmatch(line, -1) {
		if stem := strings.TrimRight(m[2], " \t§"); !defined[stem] {
			refs = append(refs, stem)
		}
	}
	for _, stem := range knownStemRefs(line, defined, knownStems) {
		if !slices.Contains(refs, stem) && !slices.Contains(refs, "#"+stem) {
			refs = append(refs, stem)
		}
	}
	return refs
}

// containsToken reports whether name occurs in s as a whole token, so `bar.md` in
// code does not excuse `ar.md` in a comment.
func containsToken(s, name string) bool {
	word := func(c byte) bool {
		return c == '_' || c == '-' || '0' <= c && c <= '9' || 'a' <= c && c <= 'z' || 'A' <= c && c <= 'Z'
	}
	for i := 0; ; {
		k := strings.Index(s[i:], name)
		if k < 0 {
			return false
		}
		start, end := i+k, i+k+len(name)
		if (start == 0 || !word(s[start-1]) && s[start-1] != '.') && (end == len(s) || !word(s[end])) {
			return true
		}
		i = start + 1
	}
}

// commentSpans splits a source file into its comments and the rest, by the file's
// own syntax; ok is false for a file type that carries no comments worth scanning.
func commentSpans(name string, src []byte) (spans []commentSpan, code string, ok bool) {
	switch ext := filepath.Ext(name); {
	case ext == ".go":
		spans, code = goSpans(src)
	case ext == ".ts" || ext == ".mjs" || ext == ".js":
		spans, code = cLikeSpans(src, true)
	case ext == ".css":
		spans, code = cLikeSpans(src, false)
	case ext == ".html":
		spans, code = htmlSpans(src)
	case hashSyntaxes[ext] != nil:
		spans, code = hashSpans(src, hashSyntaxes[ext])
	case name == "Dockerfile":
		spans, code = hashSpans(src, hashSyntaxes[".sh"])
	case name == ".gitignore":
		spans, code = hashSpans(src, &hashSyntax{})
	default:
		return nil, "", false
	}
	return spans, code, true
}

// goSpans treats a backtick raw string as prose too: the capability table's
// `because` texts live there.
func goSpans(src []byte) (spans []commentSpan, code string) {
	fset := token.NewFileSet()
	file := fset.AddFile("src.go", -1, len(src))
	var s scanner.Scanner
	s.Init(file, src, nil, scanner.ScanComments)
	var b strings.Builder
	for {
		pos, tok, lit := s.Scan()
		if tok == token.EOF {
			return spans, b.String()
		}
		if tok == token.COMMENT || (tok == token.STRING && strings.HasPrefix(lit, "`")) {
			spans = append(spans, commentSpan{text: lit, line: fset.Position(pos).Line})
			continue
		}
		b.WriteString(lit)
		b.WriteByte('\n')
	}
}

// cLikeSpans reads `/* */` (and, for JS, `//`) while stepping over quoted strings and
// JS regex literals, so a `//` inside a URL string is not a comment. A JS template
// literal's text is skipped, but each `${…}` inside it is source, where a comment can sit.
func cLikeSpans(src []byte, js bool) (spans []commentSpan, code string) {
	s := string(src)
	var b strings.Builder
	line := 1
	emit := func(lit string) {
		b.WriteString(lit)
		line += strings.Count(lit, "\n")
	}
	// One entry per open template literal (-1) or `${` expression (its count of open
	// braces); a `}` closes the expression only at a count of zero.
	var nest []int
	var prev byte // the last source byte that is not blank: after an operand, `/` divides
	for i := 0; i < len(s); i++ {
		c := s[i]
		top := len(nest) - 1
		if js && top >= 0 && nest[top] < 0 {
			switch {
			case c == '\\':
				emit(s[i:min(i+2, len(s))])
				i++
			case c == '`':
				nest = nest[:top]
				emit("`")
				prev = '`'
			case c == '$' && i+1 < len(s) && s[i+1] == '{':
				nest = append(nest, 0)
				emit("${")
				prev = '{'
				i++
			default:
				emit(s[i : i+1])
			}
			continue
		}
		switch {
		case js && c == '`':
			nest = append(nest, -1)
			emit("`")
		case js && top >= 0 && c == '{':
			nest[top]++
			emit("{")
		case js && top >= 0 && c == '}':
			if nest[top] == 0 {
				nest = nest[:top]
			} else {
				nest[top]--
			}
			emit("}")
		case c == '"' || c == '\'':
			j := i + 1
			for j < len(s) && s[j] != c && s[j] != '\n' {
				if s[j] == '\\' {
					j++
				}
				j++
			}
			stop := min(j+1, len(s))
			emit(s[i:stop])
			i = stop - 1
		case c == '/' && i+1 < len(s) && s[i+1] == '*':
			end := strings.Index(s[i+2:], "*/")
			stop := len(s)
			if end >= 0 {
				stop = i + 2 + end + 2
			}
			spans = append(spans, commentSpan{text: s[i:stop], line: line})
			line += strings.Count(s[i:stop], "\n")
			i = stop - 1
			continue
		case js && c == '/' && i+1 < len(s) && s[i+1] == '/':
			end := strings.IndexByte(s[i:], '\n')
			if end < 0 {
				end = len(s) - i
			}
			spans = append(spans, commentSpan{text: s[i : i+end], line: line})
			i += end - 1
			continue
		case js && c == '/' && (prev == 0 || strings.IndexByte("(,=:[!&|?{};+-*%<>~^", prev) >= 0):
			j, class := i+1, false
			for j < len(s) && s[j] != '\n' && (class || s[j] != '/') {
				switch s[j] {
				case '\\':
					j++
				case '[':
					class = true
				case ']':
					class = false
				}
				j++
			}
			stop := min(j+1, len(s))
			emit(s[i:stop])
			i = stop - 1
		default:
			emit(s[i : i+1])
		}
		if s[i] != ' ' && s[i] != '\t' && s[i] != '\n' && s[i] != '\r' {
			prev = s[i]
		}
	}
	return spans, b.String()
}

// hashSyntax is where a `#` starts a comment and what a string looks like, per file
// type: a `#` inside a string is not a comment, and a shell `${#n}` is not either.
type hashSyntax struct {
	inline      func(prev byte) bool // may a `#` after prev start a comment mid-line
	escapes     map[byte]bool        // quotes inside which a backslash escapes
	bareEscape  bool                 // a backslash outside quotes escapes the next byte
	triple      bool                 // triple-quoted strings, either quote
	tripleProse bool                 // and they are prose (Python docstrings)
}

func anyByte(byte) bool { return true }

func afterBlank(prev byte) bool { return prev == ' ' || prev == '\t' }

var hashSyntaxes = map[string]*hashSyntax{
	".py":   {inline: anyByte, escapes: map[byte]bool{'"': true, '\'': true}, triple: true, tripleProse: true},
	".toml": {inline: anyByte, escapes: map[byte]bool{'"': true}, triple: true},
	".yaml": {inline: afterBlank, escapes: map[byte]bool{'"': true}},
	".yml":  {inline: afterBlank, escapes: map[byte]bool{'"': true}},
	".sh": {
		inline:     func(prev byte) bool { return afterBlank(prev) || strings.IndexByte(";&|()", prev) >= 0 },
		escapes:    map[byte]bool{'"': true},
		bareEscape: true,
	},
}

// hashSpans reads `#` comments: a `#` that opens a line, or one outside every string
// where the file type lets a comment follow code.
func hashSpans(src []byte, syn *hashSyntax) (spans []commentSpan, code string) {
	s := string(src)
	var b strings.Builder
	line := 1
	emit := func(lit string) {
		b.WriteString(lit)
		line += strings.Count(lit, "\n")
	}
	lineStart := true // only blanks since the last newline
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case syn.triple && (strings.HasPrefix(s[i:], `"""`) || strings.HasPrefix(s[i:], "'''")):
			stop := len(s)
			if end := strings.Index(s[i+3:], s[i:i+3]); end >= 0 {
				stop = i + 3 + end + 3
			}
			if syn.tripleProse {
				spans = append(spans, commentSpan{text: s[i:stop], line: line})
				line += strings.Count(s[i:stop], "\n")
			} else {
				emit(s[i:stop])
			}
			i = stop - 1
		case c == '"' || c == '\'':
			j := i + 1
			for j < len(s) && s[j] != c && s[j] != '\n' {
				if s[j] == '\\' && syn.escapes[c] {
					j++
				}
				j++
			}
			stop := min(j+1, len(s))
			emit(s[i:stop])
			i = stop - 1
		case c == '\\' && syn.bareEscape:
			stop := min(i+2, len(s))
			emit(s[i:stop])
			i = stop - 1
		case c == '#' && (lineStart || syn.inline != nil && syn.inline(s[i-1])):
			end := strings.IndexByte(s[i:], '\n')
			if end < 0 {
				end = len(s) - i
			}
			spans = append(spans, commentSpan{text: s[i : i+end], line: line})
			i += end - 1
		default:
			emit(s[i : i+1])
		}
		lineStart = c == '\n' || lineStart && (c == ' ' || c == '\t')
	}
	return spans, b.String()
}

func htmlSpans(src []byte) (spans []commentSpan, code string) {
	s := string(src)
	var b strings.Builder
	line := 1
	for {
		i := strings.Index(s, "<!--")
		if i < 0 {
			b.WriteString(s)
			return spans, b.String()
		}
		j := strings.Index(s[i:], "-->")
		if j < 0 {
			j = len(s) - i
		} else {
			j += len("-->")
		}
		line += strings.Count(s[:i], "\n")
		spans = append(spans, commentSpan{text: s[i : i+j], line: line})
		line += strings.Count(s[i:i+j], "\n")
		b.WriteString(s[:i])
		s = s[i+j:]
	}
}

// sourceFiles lists the repository's tracked files, or walks the tree when it is not
// a git checkout (a source archive). Synced CI templates, fixtures, vendored modules
// and tool scratch are not this repository's prose.
func sourceFiles(t *testing.T) []string {
	t.Helper()
	skip := func(p string) bool {
		for d := range strings.SplitSeq(filepath.ToSlash(p), "/") {
			switch d {
			case ".git", ".github", "node_modules", "testdata", ".agents", ".stryker-tmp", ".vitest", ".ruff_cache":
				return true
			}
		}
		return false
	}
	var files []string
	if out, err := exec.CommandContext(t.Context(), "git", "ls-files", "-z").Output(); err == nil {
		for p := range bytes.SplitSeq(out, []byte{0}) {
			if len(p) > 0 && !skip(string(p)) {
				files = append(files, string(p))
			}
		}
		return files
	}
	err := filepath.WalkDir(".", func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() && p != "." && skip(p) {
			return filepath.SkipDir
		}
		if !d.IsDir() {
			files = append(files, p)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("Setup: walk the tree: %v", err)
	}
	return files
}

func TestSourceComments_NameNoPrivateDocument(t *testing.T) {
	type source struct {
		path, code string
		spans      []commentSpan
	}
	files := sourceFiles(t)
	shipped := map[string]bool{}
	defined := map[string]bool{}
	var sources []source
	for _, p := range files {
		if strings.HasSuffix(p, ".md") {
			shipped[filepath.Base(p)] = true
		}
		src, err := os.ReadFile(p)
		if err != nil {
			t.Fatalf("Setup: read %s: %v", p, err)
		}
		spans, code, ok := commentSpans(filepath.Base(p), src)
		if !ok {
			continue
		}
		if p != "private_doc_refs_test.go" { // its fixtures would define every name they test
			for _, w := range codeToken.FindAllString(code, -1) {
				defined[w] = true
			}
		}
		sources = append(sources, source{path: p, code: code, spans: spans})
	}
	for _, s := range sources {
		for _, sp := range s.spans {
			for k, l := range strings.Split(sp.text, "\n") {
				for _, ref := range privateDocRefs(l, s.code, shipped, defined) {
					t.Errorf("%s:%d: %s — a comment here is public and the named document is not; "+
						"state the rule in the comment itself. If %s is a file marotte's product reads, "+
						"add it to productDocNames with its reason.", s.path, sp.line+k, ref, ref)
				}
			}
		}
	}
	if len(knownStems) < 100 {
		t.Fatalf("knownStems holds %d hashes, want more than 100: the literal is not parsing", len(knownStems))
	}
	if len(sources) < 1000 {
		t.Fatalf("scanned %d source files, want more than 1000: the file listing is broken", len(sources))
	}
}

func TestPrivateDocRefs(t *testing.T) {
	shipped := map[string]bool{"README.md": true, "hardening.md": true}
	defined := map[string]bool{"web-view": true, "kiro-foo-notes": true}
	cases := map[string]struct {
		line, code string
		want       []string
	}{
		"private steering path":         {line: "// see .kiro/steering/x.md", want: []string{".kiro/steering/x.md"}},
		"private script path":           {line: "# written by .kiro/scripts/gen.py", want: []string{".kiro/scripts/gen.py"}},
		"private brace-group path":      {line: "// (`.kiro/skills/foo/refs/{a,b}-x.mjs`)", want: []string{".kiro/skills/foo/"}},
		"private named directory":       {line: "// the runners in .kiro/skills/foo/", want: []string{".kiro/skills/foo/"}},
		"brace group at the top":        {line: "// .kiro/scripts/{a,b}.py", want: []string{".kiro/scripts/{"}},
		"bare kiro directory":           {line: "// scans .kiro/skills/ for definitions"},
		"glob over named directories":   {line: "// lists .kiro/skills/*/SKILL.md"},
		"bare private doc name":         {line: "/* (style.md) */", want: []string{"style.md"}},
		"app design doc in any arm":     {line: "// the steering/marotte-foo.md rule", want: []string{"marotte-foo.md"}},
		"steering path outside kiro":    {line: "// steering/style.md says so", want: []string{"steering/style.md"}},
		"app hash pointer":              {line: "// (see #kiro-foo-notes)", want: []string{"#kiro-foo-notes"}},
		"app hash pointer with section": {line: "// #web-terminal-foo C17", want: []string{"#web-terminal-foo"}},
		"undefined hash pointer":        {line: "// see #foo-rulebook C17", want: []string{"#foo-rulebook"}},
		"bare rulebook stem":            {line: "// (foo-rulebook §7)", want: []string{"foo-rulebook"}},
		"bare app doc section":          {line: "// marotte-foo §3 says so", want: []string{"marotte-foo"}},
		"app compound word":             {line: "// a marotte-side cache"},
		"defined name with a section":   {line: "// kiro-foo-notes §2", want: nil},
		"rulebook inside a path":        {line: "// docs/foo-rulebook.txt"},
		"shipped doc":                   {line: "// see README.md"},
		"product doc":                   {line: "// writes environment.md"},
		"product steering path":         {line: "// .kiro/steering/environment.md is generated"},
		"glob over a kiro directory":    {line: "// scans .kiro/agents/*.md"},
		"illustration name":             {line: "// e.g. steering/notes.md"},
		"element id":                    {line: "/* #web-view is the iframe */"},
		"unhyphenated hash":             {line: "// issue #12 and colour #fff"},
		"path into the docs tree":       {line: "// docs/hardening.md#tls"},
		"name inside a path":            {line: "// links to shared/canonical.md"},
		"fixture built in the file":     {line: "// the fixture's alpha.md", code: "name := \"alpha.md\""},
		"fixture path built in file":    {line: "// the fixture's alpha.md", code: "p := \".kiro/steering/alpha.md\""},
		"name only inside a longer one": {line: "/* (ar.md) */", code: "name := \"bar.md\"", want: []string{"ar.md"}},
	}
	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			got := privateDocRefs(tc.line, tc.code, shipped, defined)
			if !slices.Equal(got, tc.want) {
				t.Errorf("privateDocRefs(%q) = %q, want %q", tc.line, got, tc.want)
			}
		})
	}
}

func TestKnownStemRefs(t *testing.T) {
	stems := map[string]bool{stemHash("foo-notes"): true, stemHash("style"): true, stemHash("web-terminal-ui"): true}
	cases := map[string]struct {
		line    string
		defined map[string]bool
		want    []string
	}{
		"hyphenated stem bare":           {line: "// see foo-notes for the rule", want: []string{"foo-notes"}},
		"hyphenated stem ends a line":    {line: "// the rule is in foo-notes.", want: []string{"foo-notes"}},
		"hyphenated stem with section":   {line: "// foo-notes \"Headings\"", want: []string{"foo-notes"}},
		"stem inside a path":             {line: "// docs/foo-notes.txt and foo-notes/x"},
		"stem after a slash":             {line: "// read docs/foo-notes first"},
		"stem with a file extension":     {line: "// foo-notes.go holds it"},
		"stem inside a longer word":      {line: "// a foo-notes-cache and Xfoo-notes"},
		"defined stem bare":              {line: "// the foo-notes value", defined: map[string]bool{"foo-notes": true}},
		"defined stem with section":      {line: "// foo-notes §2", defined: map[string]bool{"foo-notes": true}, want: []string{"foo-notes"}},
		"word stem bare":                 {line: "// the style of a row"},
		"word stem with quoted title":    {line: "// (style \"Headings\")", want: []string{"style"}},
		"word stem with section":         {line: "// style §2", want: []string{"style"}},
		"word stem as a hash pointer":    {line: "// see #style", want: []string{"style"}},
		"word stem with lowercase quote": {line: "// style \"x\" here"},
		"public project bare":            {line: "// the web-terminal-ui grid"},
		"public project with section":    {line: "// web-terminal-ui \"Grid\"", want: []string{"web-terminal-ui"}},
		"unknown stem":                   {line: "// bar-notes \"Headings\" and fooz §1"},
	}
	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			got := knownStemRefs(tc.line, tc.defined, stems)
			if !slices.Equal(got, tc.want) {
				t.Errorf("knownStemRefs(%q) = %q, want %q", tc.line, got, tc.want)
			}
		})
	}
}

func TestCommentSpans(t *testing.T) {
	cases := map[string]struct {
		file, src string
		want      []commentSpan
	}{
		"ts string holding slashes":           {file: "a.ts", src: "const u = \"http://x\"; // real\n", want: []commentSpan{{"// real", 1}}},
		"ts template literal":                 {file: "a.ts", src: "const t = `\n// not\n`;\n/* yes */\n", want: []commentSpan{{"/* yes */", 4}}},
		"css block comment":                   {file: "a.css", src: "a {}\n/* c */\n", want: []commentSpan{{"/* c */", 2}}},
		"css has no line comment":             {file: "a.css", src: "a { b: url(//x); }\n"},
		"go double-quoted string":             {file: "a.go", src: "package p\nvar s = \"// no\"\n"},
		"go raw string":                       {file: "a.go", src: "package p\nvar s = `raw`\n", want: []commentSpan{{"`raw`", 2}}},
		"ts regex literal holding a quote":    {file: "a.ts", src: "const r = /\"/g; // real\n", want: []commentSpan{{"// real", 1}}},
		"ts division is not a regex":          {file: "a.ts", src: "const h = w / 2; // real /x/\n", want: []commentSpan{{"// real /x/", 1}}},
		"ts comment in a template expression": {file: "a.ts", src: "const x = `${v /* c */}`;\n", want: []commentSpan{{"/* c */", 1}}},
		"ts template nested in an expression": {file: "a.ts", src: "`a${`/* no ${c} */` /* d */}e` // f\n", want: []commentSpan{{"/* d */", 1}, {"// f", 1}}},
		"ts braces inside an expression":      {file: "a.ts", src: "`${ {a: 1}.a /* c */ }`\n", want: []commentSpan{{"/* c */", 1}}},
		"shell comment after code":            {file: "a.sh", src: "x=1 # why\n", want: []commentSpan{{"# why", 1}}},
		"shell comment after a quoted word":   {file: "a.sh", src: "echo \"x\" # why\n", want: []commentSpan{{"# why", 1}}},
		"shell hash inside quotes":            {file: "a.sh", src: "echo \"a #b\"\n"},
		"shell hash inside a word":            {file: "a.sh", src: "echo ${#arr[@]} a#b\n"},
		"python comment after a string":       {file: "a.py", src: "v = \"x\" # why\n", want: []commentSpan{{"# why", 1}}},
		"python comment with no space":        {file: "a.py", src: "v = 1# why\n", want: []commentSpan{{"# why", 1}}},
		"python docstring":                    {file: "a.py", src: "def f():\n    \"\"\"Doc.\"\"\"\n", want: []commentSpan{{"\"\"\"Doc.\"\"\"", 2}}},
		"toml multi-line string is data":      {file: "a.toml", src: "body = \"\"\"\n# heading\n\"\"\"\n"},
		"toml comment after a string":         {file: "a.toml", src: "k = \"v\"# why\n", want: []commentSpan{{"# why", 1}}},
		"yaml hash inside a url":              {file: "a.yaml", src: "u: http://x/#frag # why\n", want: []commentSpan{{"# why", 1}}},
		"gitignore hash mid-line":             {file: ".gitignore", src: "a#b\n# c\n", want: []commentSpan{{"# c", 2}}},
		"html comment on a later line":        {file: "a.html", src: "<p>\n<!-- c -->\n", want: []commentSpan{{"<!-- c -->", 2}}},
		"dockerfile by name":                  {file: "Dockerfile", src: "# c\nRUN x\n", want: []commentSpan{{"# c", 1}}},
	}
	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			got, _, ok := commentSpans(tc.file, []byte(tc.src))
			if !ok {
				t.Fatalf("commentSpans(%q) did not recognise the file type", tc.file)
			}
			if !slices.Equal(got, tc.want) {
				t.Errorf("commentSpans(%q, %q) = %+v, want %+v", tc.file, tc.src, got, tc.want)
			}
		})
	}
}
