// The `vi.mock` ratchet: a whole-module factory mirrors an export list nothing keeps in step, so
// the offending set may only SHRINK. A file outside the baseline must spread `importOriginal`,
// and an entry that stops offending must leave the baseline in the same change. The scan
// balances parens (a factory body spans lines and nests); the baseline is generated by it:
//   VI_MOCK_BASELINE_UPDATE=1 npx vitest --run __test-helpers__/vi-mock-original
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = join(import.meta.dirname, "..");
const BASELINE = join(import.meta.dirname, "vi-mock-baseline.json");
const GENERATOR = "VI_MOCK_BASELINE_UPDATE=1 npx vitest --run __test-helpers__/vi-mock-original";

/** No source of this package; `.stryker-tmp` is a second copy of every test file. */
const SKIP_DIRS = new Set(["node_modules", ".vitest", ".stryker-tmp", "coverage"]);

/** Excluded: it quotes both shapes as source text, so it would be its own first offender. */
const SELF = relative(ROOT, new URL(import.meta.url).pathname);

function testFiles(dir: string, out: string[] = []): string[] {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) {
      if (!SKIP_DIRS.has(e.name)) testFiles(join(dir, e.name), out);
    } else if (e.name.endsWith(".test.ts")) {
      out.push(join(dir, e.name));
    }
  }
  return out;
}

/** Index of the closing quote of the literal opening at `i`. A template literal is skipped WHOLE,
 *  `${…}` included, so no `(` inside a string moves the paren depth. */
function skipString(src: string, i: number): number {
  const quote = src[i];
  for (let j = i + 1; j < src.length; j++) {
    if (src[j] === "\\") {
      j++;
      continue;
    }
    if (src[j] === quote) return j;
  }
  return src.length;
}

interface Args {
  /** Everything between the call's own parentheses. */
  readonly text: string;
  /** Commas at the call's own depth, so a factory is `count > 0` rather than a guess
   *  over a body that is full of commas of its own. */
  readonly commas: number;
}

/** The argument list of the call whose `(` sits at `open`, read by balancing brackets
 *  while skipping strings and comments. `null` for an unterminated call. */
function callArgs(src: string, open: number): Args | null {
  let depth = 0;
  let commas = 0;
  for (let i = open; i < src.length; i++) {
    const c = src[i];
    if (c === '"' || c === "'" || c === "`") {
      i = skipString(src, i);
      continue;
    }
    if (c === "/" && src[i + 1] === "/") {
      const nl = src.indexOf("\n", i);
      if (nl < 0) return null;
      i = nl;
      continue;
    }
    if (c === "/" && src[i + 1] === "*") {
      const end = src.indexOf("*/", i + 2);
      if (end < 0) return null;
      i = end + 1;
      continue;
    }
    if (c === "(" || c === "[" || c === "{") {
      depth++;
    } else if (c === ")" || c === "]" || c === "}") {
      depth--;
      if (depth === 0) return { text: src.slice(open + 1, i), commas };
    } else if (c === "," && depth === 1) {
      commas++;
    }
  }
  return null;
}

/** The first argument's path, as a bare string literal or the type-safe `import("./x.js")` form.
 *  `null` for anything else, judged as NOT offending: the rule governs only shapes it can read. */
function firstSpecifier(args: string): string | null {
  const m = /^\s*(?:import\s*\(\s*)?(['"])(.*?)\1/.exec(args);
  return m?.[2] ?? null;
}

interface MockSite {
  readonly specifier: string | null;
  readonly hasFactory: boolean;
  readonly spreadsOriginal: boolean;
}

/** Both verbs vitest offers for replacing a module with a factory. `vi.mocked(` fails the `(`
 *  test below and `vi.doUnmock` contains neither needle. A new verb is governed only by joining. */
const NEEDLES = ["vi.mock", "vi.doMock"] as const;

/** Every `vi.mock` call in one file. Unexported: knip runs with `includeEntryExports`. */
function mockSites(src: string): MockSite[] {
  const out: MockSite[] = [];
  for (let at = 0; at < src.length; at++) {
    const needle = NEEDLES.find((n) => src.startsWith(n, at));
    if (needle === undefined) continue;
    let open = at + needle.length;
    while (open < src.length && /\s/.test(src[open] ?? "")) open++;
    if (src[open] !== "(") continue;
    const args = callArgs(src, open);
    if (args === null) continue;
    out.push({
      specifier: firstSpecifier(args.text),
      hasFactory: args.commas > 0,
      spreadsOriginal: args.text.includes("importOriginal"),
    });
  }
  return out;
}

function offends(site: MockSite): boolean {
  const spec = site.specifier;
  if (spec === null) return false;
  if (!spec.startsWith("./") && !spec.startsWith("../")) return false;
  return site.hasFactory && !site.spreadsOriginal;
}

function scan(): string[] {
  const out: string[] = [];
  for (const file of testFiles(ROOT)) {
    const rel = relative(ROOT, file);
    if (rel === SELF) continue;
    if (mockSites(readFileSync(file, "utf8")).some(offends)) out.push(rel.split(sep).join("/"));
  }
  return out.sort();
}

const offenders = scan();

if (process.env["VI_MOCK_BASELINE_UPDATE"] === "1") {
  writeFileSync(BASELINE, `${JSON.stringify(offenders, null, 2)}\n`, "utf8");
}

function baseline(): string[] {
  let raw: string;
  try {
    raw = readFileSync(BASELINE, "utf8");
  } catch {
    throw new Error(`vi-mock-baseline.json is missing; generate it with: ${GENERATOR}`);
  }
  const parsed: unknown = JSON.parse(raw);
  if (!Array.isArray(parsed) || parsed.some((p) => typeof p !== "string")) {
    throw new Error(
      `vi-mock-baseline.json is not a list of paths; regenerate it with: ${GENERATOR}`,
    );
  }
  return parsed as string[];
}

describe("the vi.mock ratchet", () => {
  it("names no file outside the baseline holding an in-repo factory without an importOriginal spread", () => {
    const recorded = new Set(baseline());
    const added = offenders.filter((f) => !recorded.has(f));
    expect(
      added,
      "each file above mocks an in-repo module with a whole-module factory (`vi.mock` or " +
        "`vi.doMock`): spread the original instead — " +
        '`vi.mock("./x.js", async (importOriginal) => ({ ...(await importOriginal<typeof X>()), y }))`',
    ).toEqual([]);
  });

  it("holds no baseline entry that has stopped offending", () => {
    const live = new Set(offenders);
    const stale = baseline().filter((f) => !live.has(f));
    expect(
      stale,
      `each file above no longer offends (or no longer exists): remove it from ` +
        `__test-helpers__/vi-mock-baseline.json in the same change, so the baseline cannot rot ` +
        `into a permanent exemption (regenerate with: ${GENERATOR})`,
    ).toEqual([]);
  });

  it("reads both shapes off a factory body, so the empty lists above mean something", () => {
    const whole = `vi.mock("./store.js", () => ({ getActive: m.getActive }));`;
    const spread = [
      `vi.mock("../run-store.js", async (importOriginal) => ({`,
      `  ...(await importOriginal<typeof RunStore>()),`,
      `  rebuildLiveRuns: mockRebuildLiveRuns,`,
      `}));`,
    ].join("\n");
    // The type-safe spelling: the specifier is a dynamic `import()`, not a bare string.
    const typed = `vi.mock(import("./api-client.js"), () => ({ apiGet: vi.fn() }));`;
    const typedSpread = [
      `vi.mock(import("./api-client.js"), async (importOriginal) => {`,
      `  const actual = await importOriginal();`,
      `  return { ...actual, apiGet: vi.fn() };`,
      `});`,
    ].join("\n");
    const bare = `vi.mock("./store.js");`;
    const pkg = `vi.mock("@cplieger/actions", () => ({ defineAction: vi.fn() }));`;
    const stringy = `vi.mock("./store.js", () => ({ label: "a ) ( ," }));`;
    // The DEFERRED verb reaches the identical defect.
    const deferred = `vi.doMock("./editor-openers.js", () => ({ openFile: noop }));`;
    const deferredSpread = [
      `vi.doMock("./scroll.js", async (importOriginal) => ({`,
      `  ...(await importOriginal<typeof Scroll>()),`,
      `  setUserScrolledUp: noop,`,
      `}));`,
    ].join("\n");
    // `vi.doUnmock` takes no factory and must not be read as a governed verb.
    const unmock = `vi.doUnmock("./store.js");`;

    expect(mockSites(whole).map(offends)).toEqual([true]);
    expect(mockSites(spread).map(offends)).toEqual([false]);
    expect(mockSites(typed).map(offends)).toEqual([true]);
    expect(mockSites(typedSpread).map(offends)).toEqual([false]);
    expect(mockSites(bare).map(offends)).toEqual([false]);
    expect(mockSites(pkg).map(offends)).toEqual([false]);
    expect(mockSites(stringy).map(offends)).toEqual([true]);
    expect(mockSites(deferred).map(offends)).toEqual([true]);
    expect(mockSites(deferredSpread).map(offends)).toEqual([false]);
    expect(mockSites(unmock)).toEqual([]);
    expect(mockSites(`${whole}\n${spread}\n${bare}`)).toHaveLength(3);
    expect(mockSites(`${deferred}\n${whole}`).map(offends)).toEqual([true, true]);
  });
});
