// The `vi.mock` ratchet: a whole-module factory is a hand-maintained mirror of a module's
// export list, and a factory that stops naming an export production gained fails its
// suite at collection. So the set only SHRINKS: a file outside the baseline must spread
// `importOriginal`, and an entry that stops offending leaves the baseline in the same
// change. The scan is a balanced-paren read, because a factory body spans lines and nests,
// and the baseline is generated by it, never transcribed:
//
//   VI_MOCK_BASELINE_UPDATE=1 npx vitest --run __test-helpers__/vi-mock-original
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = join(import.meta.dirname, "..");
const BASELINE = join(import.meta.dirname, "vi-mock-baseline.json");
const GENERATOR = "VI_MOCK_BASELINE_UPDATE=1 npx vitest --run __test-helpers__/vi-mock-original";

/** Directories holding no source of this package: dependencies, vitest's own output,
 *  and Stryker's in-place backup, which is a second copy of every test file. */
const SKIP_DIRS = new Set(["node_modules", ".vitest", ".stryker-tmp", "coverage"]);

/** This file is excluded from its own population: it quotes the two shapes as source
 *  text, so the enforcer would be its own first offender. It mocks nothing. */
const SELF = relative(ROOT, new URL(import.meta.url).pathname);

function testFiles(dir: string, out: string[] = []): string[] {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) {
      if (!SKIP_DIRS.has(e.name)) testFiles(join(dir, e.name), out);
    } else if (e.name.endsWith(".test.ts")) {
      out.push(join(dir, e.name));
    }
  }
  return out;
}

/** Index of the closing quote of the literal opening at `i`. A template literal is
 *  skipped WHOLE, `${…}` included: the point of the skip is that nothing inside a
 *  string may move the paren depth, and a `(` in interpolated text would. */
function skipString(src: string, i: number): number {
  const quote = src[i];
  for (let j = i + 1; j < src.length; j++) {
    if (src[j] === "\\") {
      j++;
      continue;
    }
    if (src[j] === quote) return j;
  }
  return src.length;
}

interface Args {
  /** Everything between the call's own parentheses. */
  readonly text: string;
  /** Commas at the call's own depth, so a factory is `count > 0` rather than a guess
   *  over a body that is full of commas of its own. */
  readonly commas: number;
}

/** The argument list of the call whose `(` sits at `open`, read by balancing brackets
 *  while skipping strings and comments. `null` for an unterminated call. */
function callArgs(src: string, open: number): Args | null {
  let depth = 0;
  let commas = 0;
  for (let i = open; i < src.length; i++) {
    const c = src[i];
    if (c === '"' || c === "'" || c === "`") {
      i = skipString(src, i);
      continue;
    }
    if (c === "/" && src[i + 1] === "/") {
      const nl = src.indexOf("\n", i);
      if (nl < 0) return null;
      i = nl;
      continue;
    }
    if (c === "/" && src[i + 1] === "*") {
      const end = src.indexOf("*/", i + 2);
      if (end < 0) return null;
      i = end + 1;
      continue;
    }
    if (c === "(" || c === "[" || c === "{") {
      depth++;
    } else if (c === ")" || c === "]" || c === "}") {
      depth--;
      if (depth === 0) return { text: src.slice(open + 1, i), commas };
    } else if (c === "," && depth === 1) {
      commas++;
    }
  }
  return null;
}

/** The first argument's path, in both spellings vitest accepts: a bare string literal,
 *  and the type-safe `import("./x.js")` form two files in this tree already use. `null`
 *  for anything else (a variable or a template literal is not a path this rule can
 *  read), which is judged as NOT offending — the rule states the shapes it governs
 *  rather than guessing at one it cannot see. */
function firstSpecifier(args: string): string | null {
  const m = /^\s*(?:import\s*\(\s*)?(['"])(.*?)\1/.exec(args);
  return m?.[2] ?? null;
}

interface MockSite {
  readonly specifier: string | null;
  readonly hasFactory: boolean;
  readonly spreadsOriginal: boolean;
}

/** The two verbs vitest offers for replacing a module, both of which take a factory
 *  and so reach the identical defect. `vi.doMock` is not a narrower case: one file in
 *  this tree mocks four in-repo modules with whole-module factories and uses ONLY that
 *  spelling, so a needle set holding the hoisted verb alone judged none of them. Two
 *  adjacent spellings cannot false-match either needle: `vi.mocked(` fails the `(`
 *  test below (the character after the needle is `e`), and `vi.doUnmock` contains
 *  neither string. A verb vitest adds later is governed only by joining this list. */
const NEEDLES = ["vi.mock", "vi.doMock"] as const;

/** Every `vi.mock` call in one file. Unexported: its guard-the-guard case is in this
 *  same file, and knip runs with `includeEntryExports`, so an export nothing outside
 *  reads is a gate failure rather than surface. */
function mockSites(src: string): MockSite[] {
  const out: MockSite[] = [];
  for (let at = 0; at < src.length; at++) {
    const needle = NEEDLES.find((n) => src.startsWith(n, at));
    if (needle === undefined) continue;
    let open = at + needle.length;
    while (open < src.length && /\s/.test(src[open] ?? "")) open++;
    if (src[open] !== "(") continue;
    const args = callArgs(src, open);
    if (args === null) continue;
    out.push({
      specifier: firstSpecifier(args.text),
      hasFactory: args.commas > 0,
      spreadsOriginal: args.text.includes("importOriginal"),
    });
  }
  return out;
}

function offends(site: MockSite): boolean {
  const spec = site.specifier;
  if (spec === null) return false;
  if (!spec.startsWith("./") && !spec.startsWith("../")) return false;
  return site.hasFactory && !site.spreadsOriginal;
}

function scan(): string[] {
  const out: string[] = [];
  for (const file of testFiles(ROOT)) {
    const rel = relative(ROOT, file);
    if (rel === SELF) continue;
    if (mockSites(readFileSync(file, "utf8")).some(offends)) out.push(rel.split(sep).join("/"));
  }
  return out.sort();
}

const offenders = scan();

if (process.env["VI_MOCK_BASELINE_UPDATE"] === "1") {
  writeFileSync(BASELINE, `${JSON.stringify(offenders, null, 2)}\n`, "utf8");
}

function baseline(): string[] {
  let raw: string;
  try {
    raw = readFileSync(BASELINE, "utf8");
  } catch {
    throw new Error(`vi-mock-baseline.json is missing; generate it with: ${GENERATOR}`);
  }
  const parsed: unknown = JSON.parse(raw);
  if (!Array.isArray(parsed) || parsed.some((p) => typeof p !== "string")) {
    throw new Error(
      `vi-mock-baseline.json is not a list of paths; regenerate it with: ${GENERATOR}`,
    );
  }
  return parsed as string[];
}

describe("the vi.mock ratchet", () => {
  it("names no file outside the baseline holding an in-repo factory without an importOriginal spread", () => {
    const recorded = new Set(baseline());
    const added = offenders.filter((f) => !recorded.has(f));
    expect(
      added,
      "each file above mocks an in-repo module with a whole-module factory (`vi.mock` or " +
        "`vi.doMock`): spread the original instead — " +
        '`vi.mock("./x.js", async (importOriginal) => ({ ...(await importOriginal<typeof X>()), y }))`',
    ).toEqual([]);
  });

  it("holds no baseline entry that has stopped offending", () => {
    const live = new Set(offenders);
    const stale = baseline().filter((f) => !live.has(f));
    expect(
      stale,
      `each file above no longer offends (or no longer exists): remove it from ` +
        `__test-helpers__/vi-mock-baseline.json in the same change, so the baseline cannot rot ` +
        `into a permanent exemption (regenerate with: ${GENERATOR})`,
    ).toEqual([]);
  });

  it("reads both shapes off a factory body, so the empty lists above mean something", () => {
    const whole = `vi.mock("./store.js", () => ({ getActive: m.getActive }));`;
    const spread = [
      `vi.mock("../run-store.js", async (importOriginal) => ({`,
      `  ...(await importOriginal<typeof RunStore>()),`,
      `  rebuildLiveRuns: mockRebuildLiveRuns,`,
      `}));`,
    ].join("\n");
    // vitest's type-safe spelling, which this repo is moving toward: the specifier is a
    // dynamic `import()` rather than a bare string, and a predicate reading only the
    // quoted form judges NEITHER of its two live users.
    const typed = `vi.mock(import("./api-client.js"), () => ({ apiGet: vi.fn() }));`;
    const typedSpread = [
      `vi.mock(import("./api-client.js"), async (importOriginal) => {`,
      `  const actual = await importOriginal();`,
      `  return { ...actual, apiGet: vi.fn() };`,
      `});`,
    ].join("\n");
    const bare = `vi.mock("./store.js");`;
    const pkg = `vi.mock("@cplieger/actions", () => ({ defineAction: vi.fn() }));`;
    const stringy = `vi.mock("./store.js", () => ({ label: "a ) ( ," }));`;
    // The DEFERRED verb, which reaches the identical defect: one file in this tree
    // mocks four in-repo modules with whole-module factories and uses only this
    // spelling, so a predicate reading `vi.mock` alone judged none of them.
    const deferred = `vi.doMock("./editor-openers.js", () => ({ openFile: noop }));`;
    const deferredSpread = [
      `vi.doMock("./scroll.js", async (importOriginal) => ({`,
      `  ...(await importOriginal<typeof Scroll>()),`,
      `  setUserScrolledUp: noop,`,
      `}));`,
    ].join("\n");
    // `vi.doUnmock` takes no factory and is not governed; it must not be read as
    // one of the two verbs that are, and 15 sites in this tree use it.
    const unmock = `vi.doUnmock("./store.js");`;

    expect(mockSites(whole).map(offends)).toEqual([true]);
    expect(mockSites(spread).map(offends)).toEqual([false]);
    expect(mockSites(typed).map(offends)).toEqual([true]);
    expect(mockSites(typedSpread).map(offends)).toEqual([false]);
    expect(mockSites(bare).map(offends)).toEqual([false]);
    expect(mockSites(pkg).map(offends)).toEqual([false]);
    expect(mockSites(stringy).map(offends)).toEqual([true]);
    expect(mockSites(deferred).map(offends)).toEqual([true]);
    expect(mockSites(deferredSpread).map(offends)).toEqual([false]);
    expect(mockSites(unmock)).toEqual([]);
    expect(mockSites(`${whole}\n${spread}\n${bare}`)).toHaveLength(3);
    // Both verbs in one file, read in SOURCE order rather than grouped by verb.
    expect(mockSites(`${deferred}\n${whole}`).map(offends)).toEqual([true, true]);
  });
});
