// The ANSI palette's floors, measured. css/15-ansi.css reads only the theme-split
// --c-term-* tokens (hardcoded literals cannot track the theme). The maths is shelled out
// to scripts/css-contrast.py (`ansi-check --tsv`, one process for every check), which
// READS 15-ansi.css. The 32 tokens are GENERATED by scripts/css-ansi-palette.py from
// kitty's palette plus web-terminal-engine's contrast lift, and the floors are measured
// independently, so the generator and the report fail when they disagree. Node env.

import { describe, it, expect } from "vitest";
import { execFileSync } from "node:child_process";
import { readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const script = join(here, "..", "scripts", "css-contrast.py");
const generator = join(here, "..", "scripts", "css-ansi-palette.py");
const sheet = join(here, "css", "15-ansi.css");

interface Row {
  kind: string;
  theme: string;
  name: string;
  context: string;
  fg: string;
  bg: string;
  ratio: number;
  floor: number | null;
  verdict: string;
}

function rows(): Row[] {
  const out = execFileSync("python3", [script, "ansi-check", "--tsv"], { encoding: "utf8" });
  const parsed = out
    .trim()
    .split("\n")
    .map((line) => {
      const c = line.split("\t");
      return {
        kind: c[0] ?? "",
        theme: c[1] ?? "",
        name: c[2] ?? "",
        context: c[3] ?? "",
        fg: c[4] ?? "",
        bg: c[5] ?? "",
        ratio: Number(c[6]),
        floor: c[7] === "-" ? null : Number(c[7]),
        verdict: c[8] ?? "",
      };
    });
  expect(parsed.length, "the script produced no measurements").toBeGreaterThan(0);
  expect(
    [...new Set(parsed.map((r) => r.theme))].sort(),
    "both themes must be measured — a palette correct in one is the defect",
  ).toEqual(["dark", "light"]);
  return parsed;
}

/** The generator's kitty -> shipped audit, one row per token. */
function tableRows(): string[][] {
  return execFileSync("python3", [generator, "table"], { encoding: "utf8" })
    .trim()
    .split("\n")
    .slice(1)
    .map((line) => line.split("\t"));
}

function expandHex(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  const full = h.length === 3 ? [...h].map((c) => c + c).join("") : h;
  expect(full, `unexpected hex shape: ${hex}`).toMatch(/^[0-9a-f]{6}$/);
  return [0, 2, 4].map((i) => parseInt(full.slice(i, i + 2), 16)) as [number, number, number];
}

const CODES = [
  "black",
  "red",
  "green",
  "yellow",
  "blue",
  "magenta",
  "cyan",
  "white",
  "bright-black",
  "bright-red",
  "bright-green",
  "bright-yellow",
  "bright-blue",
  "bright-magenta",
  "bright-cyan",
  "bright-white",
];

const stripComments = (css: string): string => css.replace(/\/\*[\s\S]*?\*\//g, " ");

describe.skipIf(!existsSync(script))("the ANSI palette", () => {
  it("carries no colour literal — every entry reads a token", () => {
    // A colour literal cannot track the theme. Scoped to COLOUR declarations.
    const text = stripComments(readFileSync(sheet, "utf8"));
    const offenders: string[] = [];
    text.split("\n").forEach((line, i) => {
      // Any colour value but a var() read fails, except `transparent`: the ABSENCE of ink
      // (`.ansi-hidden`), which declares no part of the palette.
      const m = /(?:^|[\s;{])(color|background-color|background)\s*:\s*([^;}]+)/.exec(line);
      if (m && !/^var\(/.test(m[2]!.trim()) && m[2]!.trim() !== "transparent") {
        offenders.push(`15-ansi.css:${i + 1} ${m[1]}: ${m[2]!.trim()}`);
      }
      // A raw colour anywhere else in the file (a shadow, a gradient stop).
      for (const lit of line.matchAll(/#[0-9a-fA-F]{3,8}\b|\b(?:rgba?|hsla?|oklab)\(/g)) {
        offenders.push(`15-ansi.css:${i + 1} ${lit[0]}`);
      }
    });
    expect(
      offenders,
      "15-ansi.css must read --c-term-* for every colour. A literal here is a " +
        "second declaration of the palette, and only the token copy is theme-split.",
    ).toEqual([]);
  });

  it("declares all 16 codes in both roles, so no code falls back to the default ink", () => {
    // A missing class is invisible: the span silently inherits, reading as "no colour used".
    const text = stripComments(readFileSync(sheet, "utf8"));
    const missing: string[] = [];
    for (const code of CODES) {
      for (const role of ["fg", "bg"] as const) {
        const prop = role === "fg" ? "color" : "background-color";
        const re = new RegExp(`\\.ansi-${code}-${role}\\s*\\{[^}]*${prop}\\s*:\\s*var\\(--c-term-`);
        if (!re.test(text)) {
          missing.push(`.ansi-${code}-${role}`);
        }
      }
    }
    expect(missing, "every ANSI code needs both an ink and a fill").toEqual([]);
  });

  it("declares every attribute class output-render.ts can emit", () => {
    // An unstyled attribute class silently drops a strikethrough or conceal. ATTR_* in
    // output-render.ts is the authority for the list.
    const text = stripComments(readFileSync(sheet, "utf8"));
    const missing = [
      "ansi-bold",
      "ansi-dim",
      "ansi-italic",
      "ansi-underline",
      "ansi-double-underline",
      "ansi-overline",
      "ansi-strike",
      "ansi-hidden",
      "ansi-blink",
      "ansi-inverse-ink",
      "ansi-inverse-fill",
    ].filter((cls) => !new RegExp(`\\.${cls}\\s*\\{[^}]*[a-z]`).test(text));
    expect(missing, "an attribute output-render.ts emits must have a rule").toEqual([]);
  });

  it("keeps the inverse fallbacks out of the palette namespace, one property each", () => {
    // NAMESPACE: `.ansi-<x>-fg` / `-bg` is the 16-code palette css-contrast.py parses, so
    // default-colour fallbacks must not take that shape. ONE PROPERTY EACH: a rule setting
    // both would override a half-explicit inverse's palette class.
    const src = stripComments(readFileSync(sheet, "utf8"));
    expect(
      /\.ansi-inverse-(fg|bg)\s*\{/.test(src),
      "inverse must not use the palette suffixes",
    ).toBe(false);
    for (const [cls, prop, banned] of [
      ["ansi-inverse-ink", "color", "background-color"],
      ["ansi-inverse-fill", "background-color", "color"],
    ] as const) {
      const body = new RegExp(`\\.${cls}\\s*\\{([^}]*)\\}`).exec(src)?.[1] ?? "";
      expect(new RegExp(`(?<![-\\w])${prop}\\s*:`).test(body), `${cls} must set ${prop}`).toBe(
        true,
      );
      expect(
        new RegExp(`(?<![-\\w])${banned}\\s*:`).test(body),
        `${cls} must NOT also set ${banned} — that overrides the explicit side`,
      ).toBe(false);
    }
  });

  it("clears 4.5:1 for every ink on the surface it renders on, in both themes", () => {
    // ONE surface: `.tool-output pre` paints nothing and resolves to `.tool-call`'s
    // --c-bg-secondary. The live shell panel paints server-resolved RGB, so the count is 32.
    const misses = rows()
      .filter((r) => r.kind === "fg-surface" && r.floor !== null && r.ratio < r.floor)
      .map(
        (r) => `${r.theme} ${r.name} on ${r.context}: ${String(r.ratio)}:1 (${r.fg} on ${r.bg})`,
      );
    expect(
      misses,
      "an ANSI foreground is body text, so WCAG 1.4.3's 4.5:1 applies on the " +
        "surface it lands on — which is also the surface the generator lifts against.",
    ).toEqual([]);
    // Coverage, so a filter that silently matched nothing cannot pass this.
    const checked = rows().filter((r) => r.kind === "fg-surface");
    expect(checked.length, "16 codes x 1 surface x 2 themes").toBe(32);
  });

  it("clears 4.5:1 for every ink-on-fill pair a program can select", () => {
    // A fill is a surface a glyph sits on, so the pair matters (`ESC[34;42m` is GNU ls's
    // other-writable directory). All 16x16 are gated: a program may select any.
    const all = rows();
    const misses = all
      .filter((r) => r.kind === "fg-fill" && r.floor !== null && r.ratio < r.floor)
      .map(
        (r) => `${r.theme} ${r.name} on ${r.context}: ${String(r.ratio)}:1 (${r.fg} on ${r.bg})`,
      );
    expect(
      misses,
      "a fill is sized to CARRY a glyph. Every ink must clear 4.5:1 on every " +
        "fill, or a program that sets both renders text nobody can read.",
    ).toEqual([]);
    expect(all.filter((r) => r.kind === "fg-fill").length, "16 x 16 x 2 themes").toBe(512);
  });

  it("clears 4.5:1 for the container's own ink on every fill", () => {
    // `ESC[41m` with no colour set lands the CONTAINER's ink (--c-text-secondary) on the fill.
    const misses = rows()
      .filter((r) => r.kind === "ink-fill" && r.floor !== null && r.ratio < r.floor)
      .map((r) => `${r.theme} ${r.name} on ${r.context}: ${String(r.ratio)}:1`);
    expect(
      misses,
      "a bare ANSI background inherits the container's ink; that pair is as real " +
        "as an explicit one.",
    ).toEqual([]);
  });

  it("measures no exit-status footer, because there is no longer one to paint", () => {
    // No "status" rows: the card's own status glyph carries a command's outcome.
    expect(rows().filter((r) => r.kind === "status")).toEqual([]);
  });

  it("keeps the fill-vs-surface figures on the record without gating them", () => {
    // NOT a floor (01-tokens.css says why): a fill carrying the darkest ink at 4.5:1 cannot
    // also mark its region at 3:1. Recorded so a surface ramp change moves visible numbers.
    const recorded = rows().filter((r) => r.kind === "fill-surface");
    expect(recorded.length, "16 fills x 1 surface x 2 themes").toBe(32);
    expect(
      recorded.every((r) => r.floor === null),
      "these are recorded, not gated — gating them would be 32 standing failures",
    ).toBe(true);
    // If one ever reaches 3:1 the trade has changed and the comments are stale.
    const surprising = recorded
      .filter((r) => r.ratio >= 3.0)
      .map((r) => `${r.theme} ${r.name} on ${r.context}: ${String(r.ratio)}:1`);
    expect(
      surprising,
      "a fill reaching 3:1 against its surface would mean the arithmetic in " +
        "01-tokens.css is wrong — good news, but the comment needs rewriting.",
    ).toEqual([]);
  });

  it("ships exactly what the generator derives — a hand-edited token fails here", () => {
    // The 32 --c-term-* values are GENERATED; `check` re-derives and diffs against
    // 01-tokens.css, so a hand edit without re-running the generator fails here.
    const out = execFileSync("python3", [generator, "check"], { encoding: "utf8" });
    expect(out.trim(), "01-tokens.css drifted from scripts/css-ansi-palette.py").toBe("0 drifted");
  });

  it("anchors layer 1 on kitty's published palette, unaltered", () => {
    // The deferral, stated independently of the generator so editing its table fails: kitty's
    // options/definition.py color0-color15, the table web-terminal-engine's vt/wire.go
    // basic16RGB uses. A literal is right here: it is a claim about an external reference.
    const KITTY = [
      "#000",
      "#cc0403",
      "#19cb00",
      "#cecb00",
      "#0d73cc",
      "#cb1ed1",
      "#0dcdcd",
      "#ddd",
      "#767676",
      "#f2201f",
      "#23fd00",
      "#fffd00",
      "#1a8fff",
      "#fd28ff",
      "#14ffff",
      "#fff",
    ];
    const table = tableRows();
    expect(table.length, "16 codes x 2 roles x 2 themes").toBe(64);
    for (const theme of ["dark", "light"]) {
      for (const role of ["ink", "fill"]) {
        const seen = table.filter((r) => r[0] === theme && r[1] === role).map((r) => r[3]);
        expect(seen, `${theme} ${role} must be anchored on kitty's 16`).toEqual(KITTY);
      }
    }
  });

  it("lifts only what fails, and every ink clears the floor after the lift", () => {
    // Layer 2: every lifted ink clears 4.5:1 on its surface (web-terminal-server's
    // WithMinimumContrast floor) and the lift is MINIMAL. Counted per ORIGIN, because the four
    // light achromatic inks are authored, neither kitty's nor lifted.
    const rowsOf = tableRows();
    const under = rowsOf.filter((r) => Number(r[6]) < 4.5).map((r) => `${r[0]} ${r[2]}: ${r[6]}:1`);
    expect(under, "every derived value must clear the floor it was derived for").toEqual([]);
    const count = (theme: string, src: string): number =>
      rowsOf.filter((r) => r[0] === theme && r[1] === "ink" && r[5] === src).length;
    expect(count("dark", "kitty"), "dark: kitty's own colour on 10 of 16").toBe(10);
    expect(count("light", "kitty"), "light: only black and red are byte-exact kitty").toBe(2);
    expect(count("light", "authored"), "light: white, bright-black, bright-white").toBe(3);
    expect(
      count("dark", "authored"),
      "dark keeps three distinct achromatic levels under the lift, so it is not " +
        "authored — the asymmetry is the decision, not an oversight",
    ).toBe(0);
  });

  it("keeps the four light achromatic codes distinct and in contrast order", () => {
    // No floor catches this: the lift targets a fixed luminance, so on a light card `white`,
    // `bright-black` and `bright-white` would converge on one grey and ESC[90m and ESC[97m
    // render alike. The order is the lightness each code asks for, inverted against a light
    // card, so bright white is darkened LEAST. They stay achromatic.
    const ORDER = ["black", "bright-black", "white", "bright-white"];
    const byToken = new Map(
      tableRows()
        .filter((r) => r[0] === "light" && r[1] === "ink")
        .map((r) => [r[2], r]),
    );
    const ramp = ORDER.map((name) => {
      const row = byToken.get(`--c-term-${name}`);
      expect(row, `light --c-term-${name} must be in the generator's table`).toBeDefined();
      return { name, hex: row![4]!, ratio: Number(row![6]) };
    });

    for (const step of ramp) {
      const [r, g, b] = expandHex(step.hex);
      expect(
        [r === g, g === b],
        `${step.name} must stay achromatic — ${step.hex} has unequal channels`,
      ).toEqual([true, true]);
      expect(step.ratio, `${step.name} must clear the floor`).toBeGreaterThanOrEqual(4.5);
    }

    expect(
      new Set(ramp.map((s) => s.hex)).size,
      `the four light achromatic codes collapsed: ${ramp.map((s) => `${s.name}=${s.hex}`).join(", ")}`,
    ).toBe(4);

    const gaps = ramp.slice(1).map((s, i) => ramp[i]!.ratio - s.ratio);
    expect(
      gaps.every((g) => g > 0),
      `contrast must fall monotonically across ${ORDER.join(" > ")}: ` +
        ramp.map((s) => `${s.name} ${String(s.ratio)}`).join(", "),
    ).toBe(true);
    // A gap this small would be a compression back toward the collapse.
    expect(Math.min(...gaps), `adjacent steps too close: ${gaps.join(", ")}`).toBeGreaterThan(1.5);
  });

  it("cannot pass vacuously — the tool still reports a miss, and its verdicts are computed", () => {
    // Every floor reads a ratio out of the tool, so if it stopped measuring they would pass
    // trivially. Guard 1: the engine still fails a pair it should fail.
    expect(() =>
      execFileSync("python3", [script, "pair", "--c-text-tertiary", "--c-bg-elevated", "4.5"], {
        encoding: "utf8",
      }),
    ).toThrow();

    // Guard 2: the verdict column is derived from the ratio and the floor, not hardcoded.
    const all = rows();
    const inconsistent = all
      .filter((r) => {
        const want = r.floor === null ? "recorded" : r.ratio < r.floor ? "FAIL" : "ok";
        return r.verdict !== want;
      })
      .map((r) => `${r.theme} ${r.name} on ${r.context}: ${r.verdict} at ${String(r.ratio)}:1`);
    expect(inconsistent, "a verdict must follow from the ratio it is printed beside").toEqual([]);

    // Guard 3: both output paths agree on how much was gated.
    const summary = execFileSync("python3", [script, "ansi-check"], { encoding: "utf8" });
    const gated = all.filter((r) => r.floor !== null).length;
    expect(gated, "the gated set must not be empty").toBeGreaterThan(500);
    expect(summary.trim()).toBe(`${String(all.length)} measurements, 0 FAIL`);
  });
});
