package steering

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/cplieger/marotte/internal/workspace"
)

// lookupEnv is the environment seam the runtime section reads through.
var lookupEnv = os.LookupEnv

func writeIntro(b *strings.Builder, workDir string) {
	b.WriteString("# Environment\n\n")
	b.WriteString("Kiro Web container. Workspace: `" + workDir + "`\n\n")
	b.WriteString("This file is auto-generated by marotte (at startup, before each session start, ")
	b.WriteString("and when MCP servers or forge connections change); edits are overwritten. ")
	b.WriteString("Durable custom instructions belong in `custom.md` ")
	b.WriteString("(Settings → Custom instructions → \"Global instructions\").\n\n")
}

// envSpan renders NAME=value as one code span, or "" when the variable is unset
// or its value would break out of the span.
func envSpan(name string) string {
	v, ok := lookupEnv(name)
	if !ok || strings.ContainsAny(v, "`\n\r") {
		return ""
	}
	return "`" + name + "=" + v + "`"
}

// writeRuntime prints the live process environment rather than a copy of the
// Dockerfile's ENV lines: the generator runs inside the container, so the value
// it sees is the one every shell inherits.
func writeRuntime(b *strings.Builder, configDir string) {
	b.WriteString("## Container runtime\n\n")
	if home := envSpan("HOME"); home != "" {
		b.WriteString("- " + home)
		if kiroHome := envSpan("KIRO_HOME"); kiroHome != "" {
			b.WriteString("; " + kiroHome + " holds kiro-cli's own state: `steering/environment.md` ")
			b.WriteString("(this file), `steering/custom.md`, `settings/cli.json`, `sessions/`, logs")
		}
		b.WriteString("\n")
	}
	if p := envSpan("PATH"); p != "" {
		b.WriteString("- " + p + " as the image exports it: `" + configDir + "/tools/bin` is the tools ")
		b.WriteString("engine's single bin dir (symlinks into `" + configDir + "/tools/opt/<tool>/<version>/`), ")
		b.WriteString("`" + configDir + "/tools/go/bin` is `$GOPATH/bin`, and `$HOME/.local/bin` is the ")
		b.WriteString("per-user bin dir (`uv tool install` lands there)\n")
	}
	var rest []string
	for _, name := range []string{"GOPATH", "GOBIN", "LANG", "TZ"} {
		if s := envSpan(name); s != "" {
			rest = append(rest, s)
		}
	}
	if len(rest) > 0 {
		b.WriteString("- " + strings.Join(rest, ", ") + "\n")
	}
	b.WriteString("- `" + configDir + "` is the persistent volume: `chats/` (one directory per chat: a `chat.json` header and an `entries.jsonl` turn log), ")
	b.WriteString("`config.json` (marotte's settings), `tools.json` (tool manifest: what should be installed), ")
	b.WriteString("`tools-state.json` (what is installed), `tools/` (`bin/`, `opt/<tool>/<version>/`, ")
	b.WriteString("`go/`, `npm/`, `python/`, `kiro-cli-versions/<version>/`), `home/` (= HOME)\n")
	b.WriteString("- Every login shell, the browser Shell panel's `bash --login` included, sources ")
	b.WriteString("`/etc/profile.d/10-marotte-path.sh` (rewritten by the entrypoint each boot), so an ")
	b.WriteString("installed tool resolves by bare name there too. If a user still gets `command not found`, ")
	b.WriteString("the boot log carries a WARNING that the drop-in was not written: hand them the absolute ")
	b.WriteString("path (`" + configDir + "/tools/bin/<tool>`). Pin `HOME=" + configDir + "/home` on any command a ")
	b.WriteString("user runs that reads or writes per-user state (`git config --global`, a tool's own login): a shell ")
	b.WriteString("reached another way can carry `HOME=/root`, and a token written there is one no agent ")
	b.WriteString("session reads\n\n")
}

// 9847 mirrors internal/server's unexported port const; steering cannot import
// server (server imports steering).
func writeToolsEngine(b *strings.Builder, configDir, workDir string) {
	b.WriteString("## Tools engine\n\n")
	b.WriteString("- marotte's own HTTP server answers on `localhost:9847` inside the container (correct from ")
	b.WriteString("in here whatever the host published). `curl -s 'localhost:9847/api/tools/search?q=<name>'` ")
	b.WriteString("searches the tool catalog AND the host's Debian packages in one answer; a hit is ")
	b.WriteString("`{name, source, version?, match?, apt?, unavailable?, reason?}`, and the same name can ")
	b.WriteString("appear twice at two versions (`aqua:…` and `apt:…`), which is why both are shown\n")
	b.WriteString("- `curl -s -X POST localhost:9847/api/tools -H 'content-type: application/json' ")
	b.WriteString("-d '{\"name\":\"<name>\"}'` installs one and answers `202 {\"job\":…}`; an `apt:` hit also needs ")
	b.WriteString("its `\"source\":\"apt:<name>\"`, or the engine answers `unknown tool`; progress streams to ")
	b.WriteString("Settings → Tools, and `GET localhost:9847/api/tools/jobs` lists jobs. A catalog install ")
	b.WriteString("lands under `" + configDir + "/tools/opt/<name>/<version>/` with a symlink in ")
	b.WriteString("`" + configDir + "/tools/bin/`, is recorded in `" + configDir + "/tools.json`, and survives a ")
	b.WriteString("container recreate. An `\"apt\":true` hit is recorded too but installs into the container ")
	b.WriteString("layer, so it is re-applied at the next boot at whatever version Debian then offers. Prefer ")
	b.WriteString("the engine to a bare `apt-get install` (unrecorded, lost on recreate) for anything you ")
	b.WriteString("expect to use again, and tell the user what you installed\n")
	b.WriteString("- Add `&unavailable=1` to the search to also list catalog entries the engine cannot install ")
	b.WriteString("(each with its `reason`); those are the ones to build or install by hand\n")
	b.WriteString("- UI path for users: Settings → Tools → \"Tools & runtimes\": a switch per row (off = ")
	b.WriteString("uninstall, keep the entry as a template), \"Add tool\" (a search over the same catalog and ")
	b.WriteString("Debian packages), \"Update all\", \"Refresh catalog\"; \"MCP integrations\" sits below it ")
	b.WriteString("on the same tab. \"Advanced configuration\" → \"tools.json\" opens the manifest in the editor: a save there installs or ")
	b.WriteString("removes what changed and refuses an invalid file. ")
	if _, err := workspace.ResolveInsideAbs(workDir, filepath.Join(configDir, "tools.json")); err == nil {
		b.WriteString("A write from your own file tools gets the same check and install: an invalid one is refused with the ")
		b.WriteString("reason, so fix it and write again. ")
	} else {
		b.WriteString("Your file tools cannot write it, because `" + configDir + "` is outside the workspace. ")
	}
	b.WriteString("A shell write is neither checked nor applied until the next boot or the next save there. A `tools.json` the ")
	b.WriteString("engine refuses at boot leaves the tools engine off, with the reason in Settings → Tools and the boot log, ")
	b.WriteString("until a valid save turns it back on. Prefer the engine API above\n\n")
}

func writeGitPanel(b *strings.Builder, workDir string, connected bool) {
	b.WriteString("## Git panel\n\n")
	b.WriteString("The Git panel (toolbar \"Toggle git\", Ctrl+Shift+G, routes `/git`, `/git/prs`, ")
	b.WriteString("`/git/sources`) has three tabs:\n\n")
	b.WriteString("- **Changes**: one collapsible section per repo under `" + workDir + "`. Header: branch chip ")
	b.WriteString("(click → switch branch, or type a \"New branch name\" to create one; ✨ proposes a name), ")
	b.WriteString("ahead/behind counts, Push, Pull, Stash / Pop; the tab toolbar has \"Pull every repo that can ")
	b.WriteString("fast-forward\". Body: staged and unstaged lists with Stage / Unstage / Discard per file and ")
	b.WriteString("\"Stage all\" / \"Unstage all\" / \"Discard all\"; clicking a filename opens its diff against ")
	b.WriteString("HEAD. Commit box: a \"Commit message…\" field, a ✨ button that drafts the message from the ")
	b.WriteString("staged diff, then \"Commit N files\"\n")
	b.WriteString("- Push is a plain `git push` (no `--force`, no `-u`, no tags): on a branch with no upstream ")
	b.WriteString("it fails with git's own message, so publish the branch with `git push -u origin <branch>` ")
	b.WriteString("from the shell first; Pull is `--ff-only`. Amend, rebase, merge, tags, cherry-pick and ")
	b.WriteString("force-push have no button: use the shell. Commit identity is `$HOME/.gitconfig` ")
	b.WriteString("(`user.name`/`user.email`); marotte never writes it\n")
	b.WriteString("- **Pull requests**: per connected forge, the open PRs of the account's own repositories and ")
	b.WriteString("its other owners' (on GitLab, the account's own PRs in them), grouped by repository with their ")
	b.WriteString("CI status; \"+ New PR\" (Base branch, Head branch, Title, a description drafted for you with ")
	b.WriteString("\"Regenerate description\"), Merge (method + confirm), \"Merge when green\", \"Re-run\" ")
	b.WriteString("the failed checks, \"Close\" (the row turns into an \"Undo\" bar and the close is sent a ")
	b.WriteString("few seconds later); a collapsed \"Contributions elsewhere\" group at the end lists, ")
	b.WriteString("read only, the PRs the account opened in other repositories, each linking to the forge\n")
	b.WriteString("- **Sources**: connected forge accounts with \"Add an account\": GitHub and GitLab by ")
	b.WriteString("\"Sign in with GitHub\" / \"Sign in with GitLab\" (OAuth device flow; on GitHub Enterprise or a ")
	b.WriteString("self-managed GitLab only with an \"OAuth client ID\" its administrator registered) or a personal ")
	b.WriteString("access token, Gitea and Codeberg by token. A gitlab.com sign-in token lasts two hours; marotte ")
	b.WriteString("renews it with the refresh token when GitLab issued one, and a sign-in it cannot renew shows ")
	b.WriteString("\"Reconnect\" once it expires. Each account row has ")
	b.WriteString("\"Check\" (re-reads the account), \"Reconnect\" when the stored credential needs a new sign-in, ")
	b.WriteString("\"Sign out\", a list of other owners (\"No other owners\" until one is added with \"Owner\" and ")
	b.WriteString("\"Add\") whose pull requests the Pull requests tab also lists, and the account's repo list with ")
	b.WriteString("\"Clone into workspace\" per repo and \"Load more repositories\" while the forge has more; ")
	b.WriteString("a clone lands under ")
	b.WriteString("`" + workDir + "/<name>`. The tab's \"Refresh accounts and repositories\" button re-reads ")
	b.WriteString("every account's repo list from its forge\n\n")
	if !connected {
		b.WriteString("No forge account is connected: the Pull requests and Sources tabs list nothing until ")
		b.WriteString("the user adds one under Sources → \"Add an account\", which is also what registers marotte's ")
		b.WriteString("git credential helper `git push` needs over HTTPS\n\n")
		return
	}
	b.WriteString("Your own git access over HTTPS is the account the Sources tab holds: connecting it ")
	b.WriteString("registers marotte's git credential helper for that forge, so plain `git` against an ")
	b.WriteString("`https://` remote is authenticated with no login step\n\n")
}

// Quoted words are exact on-screen labels from static/index.html and the client
// modules; a paraphrase here sends a user looking for a control that is not there.
func writeUIGuide(b *strings.Builder) {
	b.WriteString("## UI guide\n\n")
	b.WriteString("Where things are, so you can direct a user. Quoted words are the exact labels on screen.\n\n")
	b.WriteString("- Sidebar: \"New chat\"; the tab list; footer: the account button (plan, usage meter, ")
	b.WriteString("\"Overages on/off\") and \"Log out\"; \"Toggle theme\" lives here, not in Settings; a ")
	b.WriteString("\"Touch mode\" toggle appears on desktops that have seen a touchscreen\n")
	b.WriteString("- Chat toolbar (top right): \"Search (Ctrl+F)\", \"File browser\", \"Toggle git\", ")
	b.WriteString("\"Toggle shell\", \"Kiro docs\", \"History\", \"Settings\". On a phone the ☰ \"Menu\" button ")
	b.WriteString("opens the sidebar\n")
	b.WriteString("- Tabs: the strip is server-owned and shared across every device (max 48). Eleven kinds: ")
	b.WriteString("chat, editor, files, run, subagent, spec, settings, git, docs, history, web. Drag to reorder; × or ")
	b.WriteString("middle-click closes; right-click gives \"Pin\"/\"Unpin\", \"Export as Markdown\", \"Export as ")
	b.WriteString("JSON\". Closing a chat tab ends its running turn and keeps the record while retention is ")
	b.WriteString("on; a run or subagent tab's × closes the view only\n")
	b.WriteString("- Composer: the textarea (\"Message Kiro...\"), then a pill row: context pie (click: ")
	b.WriteString("tokens, credits, turns), model pill (model + reasoning effort), mode pill (\"Default\", ")
	b.WriteString("Spec, Plan, … and every custom agent), \"Chat actions\" `+` with rows \"Attach a file\", ")
	b.WriteString("\"Start a tangent\", \"Set a goal\", \"Supervised mode\", a \"Task list\" pill while a plan ")
	b.WriteString("exists, and Send, which swaps to a cancel button (tooltip \"Cancel this turn\") while a ")
	b.WriteString("turn streams; Enter with text mid-turn steers the running turn. A prompt starting with `!` ")
	b.WriteString("runs as a shell command; `/compact` compacts the context\n")
	b.WriteString("- Turn footer: \"Copy as text\", \"Copy as markdown\", \"Copy chat ID\", \"Export chat as ")
	b.WriteString("JSON\", one row per changed file (opens its diff), and \"Rewind\" (see Chat capabilities)\n")
	b.WriteString("- Settings (gear or Ctrl+,) has four tabs: \"General\", \"Tools\", \"Permissions\", ")
	b.WriteString("\"Custom instructions\"\n")
	b.WriteString("- Settings → General → \"Notifications\": the \"Push notifications\" toggle enables browser ")
	b.WriteString("push (the browser asks for permission); under it \"Agent finished\", \"Pull request checks\" ")
	b.WriteString("and \"Workflow runs\" choose which events notify; \"Pull request checks\" starts OFF ")
	b.WriteString("because a pull request's CI verdict is already on the forge and in the PRs tab, while the ")
	b.WriteString("other two report work that happened with nobody watching; a permission ask has no switch ")
	b.WriteString("of its own and notifies whenever push is on. ")
	b.WriteString("Then \"About\" (versions, \"Run diagnostics\"), \"Chat retention\" ")
	b.WriteString("(\"Keep forever\" or \"Days kept\", default 7), \"Agent capabilities\" (\"Knowledge base ")
	b.WriteString("search\", \"Load MCP tools on demand\", \"Memory\", \"Spec planning\", ")
	b.WriteString("\"Inline helper agents\", \"Steering reminders\", \"Work validation\", ")
	b.WriteString("\"AWS CloudFormation safety check\", \"Workflows\", \"Output style\", \"Shell command timeout\"), ")
	b.WriteString("\"Data sharing\" (\"Share content with AWS for service improvement\", \"kiro-cli telemetry\"), ")
	b.WriteString("\"Experimental features\" (\"Show hook status in chat\", \"Exclude ")
	b.WriteString("default resources from custom agents\", \"Debug logs\"), \"Advanced\" (\"config.json\" opens every setting as one file in the editor)\n")
	b.WriteString("- Settings → Tools: \"Tools & runtimes\" (see Tools engine in the environment steering doc), \"Advanced configuration\" (\"tools.json\") and \"MCP integrations\" ")
	b.WriteString("(\"Connect integration\", per-server status, OAuth)\n")
	b.WriteString("- Settings → Permissions: \"Security profile\" (guarded, read-only, trusted, unrestricted, ")
	b.WriteString("custom; \"Customize\"), \"Active policy\" with \"Add a rule\" and \"Test a decision (why?)\", ")
	b.WriteString("\"Supervised mode (default for new chats)\", \"Scheduled runs\" (auto-approve for unattended ")
	b.WriteString("runs), \"Agent ignore files\"\n")
	b.WriteString("- Settings → Custom instructions: \"Global instructions\" (the textarea IS `custom.md`, ")
	b.WriteString("autosaved) and \"Knowledge bases\"\n")
	b.WriteString("- \"Kiro docs\" (`/docs`): Steering, Skills, Prompts, Agents, Specs, Hooks (enable/disable toggle, ")
	b.WriteString("open, delete), Workflows (\"Run\" ⇄ \"Cancel\" a recipe with its inputs, \"Schedule\" it), Memories ")
	b.WriteString("(review and delete; hidden while the Memory setting is Off, and `/memories` then says so), Powers\n")
	b.WriteString("- \"History\" (`/history`): previous chats and workflow runs from kiro-cli's own inventory, ")
	b.WriteString("a \"Search conversations…\" box that searches every chat file, open to resume, \"Delete\"\n")
	b.WriteString("- \"File browser\" (`/files`, Ctrl+Shift+F): mounts `/workspace`, `/config` and the uploads ")
	b.WriteString("folder; toolbar \"Back\" / \"Forward\" / path, \"Add selection to chat\", \"Upload files\", ")
	b.WriteString("\"Download\", \"New file\", \"New folder\", \"Rename (F2)\", \"Delete\"; a search mode; a git ")
	b.WriteString("status letter per row that opens the change; drag files onto it to upload. Opening a file ")
	b.WriteString("gives the editor (`/file/<path>#L<line>`): \"Edit\" / \"Save\" / \"Stop editing\", \"View as ")
	b.WriteString("diff (vs saved)\", \"View diff vs HEAD\", markdown rendered until Edit, merge markers get ")
	b.WriteString("per-hunk \"Ours\" / \"Theirs\" / \"Both\" plus \"Suggest\"\n")
	b.WriteString("- \"Toggle shell\" (Ctrl+/): one bottom-docked `bash --login` for the whole workspace, ")
	b.WriteString("shared by every tab and kept across reloads; header \"Key toolbar\", \"Restart shell\", ")
	b.WriteString("\"Full screen\", \"Close shell\"; drag its top edge to resize. Your own commands stream into ")
	b.WriteString("their tool cards, not into this shell\n")
	b.WriteString("- A Preview tab (`/web/<path>`) shows an HTML page from the workspace in a sandbox; ")
	b.WriteString("its bottom bar shows the page path, a width switcher (Fill, Phone, Tablet, Desktop), ")
	b.WriteString("\"Scale to fit\" and \"Reload preview\". The \"Open preview\" button in the editor ")
	b.WriteString("toolbar and in the file browser opens one for an `.html` file\n")
	b.WriteString("- A run tab (`/run/<id>`): header, alert, timeline, results, step tree, detail; \"Pause\" / ")
	b.WriteString("\"Resume\" / \"Cancel\" for any run, \"Retry failed steps\" only for a run no chat launched; ")
	b.WriteString("its × closes the view, never the run\n")
	b.WriteString("- Sign-in modal: \"Sign in\" (Builder ID, Google, or GitHub) or \"Sign in with SSO\" (Start ")
	b.WriteString("URL + Region)\n")
	b.WriteString("- Keyboard: Ctrl/⌘+K or N new chat, Ctrl+/ shell, Ctrl+Shift+F files, Ctrl+Shift+G git, ")
	b.WriteString("Ctrl+, settings, Ctrl+Enter send, Ctrl+F find in chat, `?` lists them\n\n")
}

// command.attachmentBlock (prompt_attachments.go) decides which extensions are
// inlined, and utils-url.ts + file-extensions.ts decide which paths paint; this
// section lies if either set moves.
func writeAttachments(b *strings.Builder, uploadDir, workDir string) {
	b.WriteString("## Images and attachments\n\n")
	b.WriteString("- How a file reaches you: the \"Attach a file\" row (a picker over the file browser; the ")
	b.WriteString("file keeps its path), a drag-drop onto the chat, or a paste into the composer. There is no ")
	b.WriteString("screenshot capture in the app: the user copies a screenshot to the clipboard with the OS ")
	b.WriteString("tool (Win+Shift+S, ⌘⌃⇧4, the GNOME/KDE tools) and pastes it\n")
	b.WriteString("- A pasted image is renamed and uploaded to ")
	b.WriteString("`" + uploadDir + "/pasted-YYYY-MM-DDTHH-MM-SS.png` (the stamp is UTC, not `TZ`; `.jpg`/`.webp` ")
	b.WriteString("when the clipboard held one); a pasted FILE keeps its own name in `" + uploadDir + "/`; a pasted ")
	b.WriteString("multi-line TEXT over 50 lines or 10,000 characters becomes `" + uploadDir + "/paste-YYYY-MM-DDTHH-MM-SS.txt` ")
	b.WriteString("and is attached instead of typed (a single line stays in the box whatever its length). Two ")
	b.WriteString("pastes inside one second share a name and the second overwrites. Upload limits: 255 MiB ")
	b.WriteString("per gesture (the total across every file in one upload), 25 files\n")
	b.WriteString("- What you receive: `.png/.jpg/.jpeg/.gif/.webp` up to 10 MiB (5 MiB base64, 15 MiB per ")
	b.WriteString("prompt, at most 16 images since the last compaction) arrive as an inline image block: you ")
	b.WriteString("SEE the picture, no tool call is needed, and the block carries NO filename. Every inlined ")
	b.WriteString("image is fitted first: one over a 2000px long edge is scaled down to it, and one still over ")
	b.WriteString("5 MiB base64 is re-encoded smaller (a JPEG stays JPEG, anything else becomes PNG). ")
	b.WriteString("`.pdf/.csv/.doc/.docx/.xls/.xlsx` arrive embedded too, as a `resource` block whose `uri` ")
	b.WriteString("is the file path. Everything else, and any image that misses a limit, arrives as the text ")
	b.WriteString("`Attached file: <path>` with the reason: read that path with your file tools. `.svg` and ")
	b.WriteString("`.avif` are never inlined\n")
	b.WriteString("- So when a user pastes an image: look at it and answer from what you see; do not ")
	b.WriteString("`read_file` it and do not say you cannot see it. When you need the FILE (to edit it, pass ")
	b.WriteString("it to a tool, or re-read it after compaction), the path is not in the prompt: the user's ")
	b.WriteString("message shows the file's pill (name shown, full path on hover), or list `" + uploadDir + "` newest-first ")
	b.WriteString("(`ls -t " + uploadDir + " | head`) and take the `pasted-<timestamp>` that matches. A ")
	b.WriteString("`paste-*.txt` attachment is text the composer spilled out of the prompt: read it, it IS ")
	b.WriteString("part of the request\n")
	b.WriteString("- Failure modes: an image the backend refuses (pixel dimensions or image count over its ")
	b.WriteString("limit, an unsupported or mismatched format; marotte fits every inlined image and caps its ")
	b.WriteString("bytes before sending, and does not check whether the model takes images) ends the turn with \"The ")
	b.WriteString("request was refused as sent. Resending it unchanged will fail the same way\": shrink or ")
	b.WriteString("drop the image, or use Rewind to remove the earlier turn that carried it, whether the user ")
	b.WriteString("attached it or a file or MCP tool returned it. Reopening the chat does not clear an image a ")
	b.WriteString("tool returned. A `.txt` where the user expected an image means the ")
	b.WriteString("clipboard carried text, not pixels\n")
	b.WriteString("- To SHOW the user an image you produced, write it as markdown: ")
	b.WriteString("`![label](" + workDir + "/out/shot.png)`. That renders inline, where a bare absolute path ")
	b.WriteString("outside backticks becomes a button that opens the file instead. The ")
	b.WriteString("path must be absolute and under `" + workDir + "/` or `" + uploadDir + "/` (never ")
	b.WriteString("`/config/`), and png/jpg/jpeg/gif/webp/svg/avif/ico/bmp all paint. Audio ")
	b.WriteString("(mp3/wav/ogg/m4a/flac/aac/opus) in the same position gets a player, any other file a ")
	b.WriteString("download link\n")
	b.WriteString("- To SHOW the user an HTML/CSS/JS demo, link its entry page with markdown and an absolute ")
	b.WriteString("path, e.g. `[Demo](" + workDir + "/demo/index.html)`. It renders as a card that opens the ")
	b.WriteString("page in a sandboxed Preview tab inside marotte. Keep the page in its own folder under `")
	b.WriteString(workDir + "` (a page directly in `" + workDir + "` is refused, because it would give the ")
	b.WriteString("preview the whole workspace), with its CSS, JS, images and JSON in that folder or below ")
	b.WriteString("it, referenced by relative paths; files and folders starting with `.` are not served and ")
	b.WriteString("symlinks are not followed. Scripts, styles, images and fonts from https CDNs load; ")
	b.WriteString("`fetch`/XHR reach only files in that folder; `localStorage`/`sessionStorage` work but ")
	b.WriteString("reset on every reload; cookies and IndexedDB are unavailable. There is no dev server or ")
	b.WriteString("port forwarding: build static output with relative asset URLs (Vite: `vite build ")
	b.WriteString("--base=./`) and link the built `index.html`. The tab reloads when files in the folder ")
	b.WriteString("change. Build responsive pages with `<meta name=\"viewport\" content=\"width=device-width\">`; ")
	b.WriteString("add `<meta name=\"marotte-preview\" content=\"phone\">` (or `tablet`, `desktop`, or a ")
	b.WriteString("pixel width such as `1280`) only when the demo should be judged at that size\n")
	b.WriteString("- To LINK any other file, write `[label](" + workDir + "/path/file.ext#L<line>)` with its ")
	b.WriteString("plain absolute path under `" + workDir + "/` or `" + uploadDir + "/` (the `#L<line>` is ")
	b.WriteString("optional): a click opens the file in a marotte editor tab, an image in the image viewer, so ")
	b.WriteString("link files that way rather than as a `/file/...` or `/api/...` URL\n\n")
}

func writeLimitations(b *strings.Builder) {
	b.WriteString("## Limitations\n\n")
	b.WriteString("- Shell commands run in the container, not on the host\n")
	b.WriteString("- No GUI or browser; web_fetch and web_search work\n")
	b.WriteString("- Container has no Docker socket\n\n")
}

func writeCapabilities(b *strings.Builder, configDir string) {
	b.WriteString("## Capabilities\n\n")
	b.WriteString("- Chat history is stored in `" + configDir + "/chats/<id>/entries.jsonl` (one directory per chat); ")
	b.WriteString("from the shell, grep the `entries.jsonl` files\n")
	b.WriteString("- You can read, write, and edit files in the workspace directly\n")
	b.WriteString("- Shell commands execute in the workspace directory\n")
}

// The agent's tool surface has no resume/retry verb; state only the
// chat-recovery path.
func writeChatCapabilities(b *strings.Builder) {
	b.WriteString("## Chat capabilities\n\n")
	b.WriteString("- In the UI, Ctrl+F searches the open chat and History → \"Search conversations…\" ")
	b.WriteString("searches every chat\n")
	b.WriteString("- Undo is per TURN, not per file: kiro-cli snapshots the files its own edit tools write ")
	b.WriteString("(never a shell write, never a manual editor save), and the user's \"Rewind\" on a turn ")
	b.WriteString("footer reverts those files AND drops that prompt and everything after it (a confirm step, ")
	b.WriteString("disabled mid-turn). There is no per-file restore\n")
	b.WriteString("- A paused workflow run recovers through the chat that launched it: this ")
	b.WriteString("server resumes a run its own chat's bridge left paused when that bridge comes ")
	b.WriteString("back, so continuing the conversation is what restarts the run. You have no ")
	b.WriteString("resume or retry tool, so do not plan around one; a run you cannot reach is ")
	b.WriteString("reported to the user, not worked around. What you CAN do to a live run is mark ")
	b.WriteString("a wedged in-flight step completed or failed so the run advances past it\n")
}
