// Code generated by cmd/wire-codegen. DO NOT EDIT.

import { registerSSEDecoder } from "../bus.js";
import { decodeAgentNoticePayload, decodeChatDeletedPayload, decodeChatHeader, decodeCodeReferencesPayload, decodeConnectedPayload, decodeDecisionSettledPayload, decodeDraftChangedPayload, decodeElicitationNeededPayload, decodeEntryAppendedPayload, decodeEntryDeltaPayload, decodeEntryOpenedPayload, decodeEntrySealedPayload, decodeErrorPayload, decodeGovernanceStatePayload, decodeInventoryChangedPayload, decodeKnowledgeIndexingPayload, decodeMCPConnectedPayload, decodeMCPDisconnectedPayload, decodeMCPFailedPayload, decodeMCPOAuthPayload, decodeNotificationPayload, decodeOpenExternalURLPayload, decodePendingSnapshotPayload, decodePermissionNeededPayload, decodePermissionsChangedPayload, decodePolicyErrorPayload, decodeRunFinishedPayload, decodeRunInputNeededPayload, decodeRunInputSettledPayload, decodeRunProgressPayload, decodeRunStartedPayload, decodeSafetyPropertiesPayload, decodeSafetyStatusPayload, decodeSpecApprovedPayload, decodeSpecChangedPayload, decodeStatusSnapshotPayload, decodeSteerQueuedPayload, decodeSystemNoticePayload, decodeTabsChangedPayload, decodeTangentMergedPayload, decodeTerminalCreatedPayload, decodeTerminalExitedPayload, decodeTerminalOutputPayload, decodeToolJobChangedPayload, decodeToolJobOutputPayload, decodeToolProgressPayload, decodeTurnClosedPayload, decodeTurnOpenedPayload, decodeUserInputNeededPayload } from "./decoders.gen.js";

export function registerAllSSEDecoders(): void {
  registerSSEDecoder("chat_created", decodeChatHeader);
  registerSSEDecoder("chat_deleted", decodeChatDeletedPayload);
  registerSSEDecoder("chat_updated", decodeChatHeader);
  registerSSEDecoder("code_references", decodeCodeReferencesPayload);
  registerSSEDecoder("connected", decodeConnectedPayload);
  registerSSEDecoder("decision_settled", decodeDecisionSettledPayload);
  registerSSEDecoder("draft_changed", decodeDraftChangedPayload);
  registerSSEDecoder("pending_snapshot", decodePendingSnapshotPayload);
  registerSSEDecoder("status_snapshot", decodeStatusSnapshotPayload);
  registerSSEDecoder("elicitation_needed", decodeElicitationNeededPayload);
  registerSSEDecoder("user_input_needed", decodeUserInputNeededPayload);
  registerSSEDecoder("error", decodeErrorPayload);
  registerSSEDecoder("governance_state", decodeGovernanceStatePayload);
  registerSSEDecoder("mcp_connected", decodeMCPConnectedPayload);
  registerSSEDecoder("mcp_disconnected", decodeMCPDisconnectedPayload);
  registerSSEDecoder("mcp_failed", decodeMCPFailedPayload);
  registerSSEDecoder("mcp_oauth_needed", decodeMCPOAuthPayload);
  registerSSEDecoder("open_external_url", decodeOpenExternalURLPayload);
  registerSSEDecoder("notification", decodeNotificationPayload);
  registerSSEDecoder("permission_needed", decodePermissionNeededPayload);
  registerSSEDecoder("permissions_changed", decodePermissionsChangedPayload);
  registerSSEDecoder("policy_error", decodePolicyErrorPayload);
  registerSSEDecoder("run_started", decodeRunStartedPayload);
  registerSSEDecoder("run_progress", decodeRunProgressPayload);
  registerSSEDecoder("run_finished", decodeRunFinishedPayload);
  registerSSEDecoder("run_input_needed", decodeRunInputNeededPayload);
  registerSSEDecoder("run_input_settled", decodeRunInputSettledPayload);
  registerSSEDecoder("safety_properties", decodeSafetyPropertiesPayload);
  registerSSEDecoder("safety_status", decodeSafetyStatusPayload);
  registerSSEDecoder("knowledge_indexing", decodeKnowledgeIndexingPayload);
  registerSSEDecoder("tool_job_changed", decodeToolJobChangedPayload);
  registerSSEDecoder("tool_job_output", decodeToolJobOutputPayload);
  registerSSEDecoder("steer_queued", decodeSteerQueuedPayload);
  registerSSEDecoder("tangent_merged", decodeTangentMergedPayload);
  registerSSEDecoder("agent_notice", decodeAgentNoticePayload);
  registerSSEDecoder("system_notice", decodeSystemNoticePayload);
  registerSSEDecoder("terminal_created", decodeTerminalCreatedPayload);
  registerSSEDecoder("terminal_output", decodeTerminalOutputPayload);
  registerSSEDecoder("terminal_exited", decodeTerminalExitedPayload);
  registerSSEDecoder("turn_opened", decodeTurnOpenedPayload);
  registerSSEDecoder("entry_opened", decodeEntryOpenedPayload);
  registerSSEDecoder("entry_delta", decodeEntryDeltaPayload);
  registerSSEDecoder("entry_sealed", decodeEntrySealedPayload);
  registerSSEDecoder("entry_appended", decodeEntryAppendedPayload);
  registerSSEDecoder("tool_progress", decodeToolProgressPayload);
  registerSSEDecoder("turn_closed", decodeTurnClosedPayload);
  registerSSEDecoder("tabs_changed", decodeTabsChangedPayload);
  registerSSEDecoder("spec_changed", decodeSpecChangedPayload);
  registerSSEDecoder("spec_approved", decodeSpecApprovedPayload);
  registerSSEDecoder("forge_inventory", decodeInventoryChangedPayload);
}
